### ISSUE TITLE
Linter doesn't support space in path

### ISSUE THREAD

**Issue by tillig** [vscode-restructuredtext/vscode-restructuredtext#162]
**Environment**
- Extension version: 110.0.0
- Visual Studio Code version: 1.36.0
- Operating System version: Windows 10
- Python version: 3.7.3

**Expected behavior**
Linting should work with files in my workspace even if the folders have spaces in the names.

**Actual behavior**
Linting appears to succeed but does not actually run.

**Detailed Steps to reproduce the problem**
- Create a folder like `C:\Projects\My Documentation\docs` - note the space in there.
- Put an RST project in there.
- Add an RST that will fail linting.
- Notice no lint errors show up.

My documents are all checked out under my `Visual Studio 2017` folder (that's just where they are, I'm not using VS 2017, I'm using VS Code).

In the output window I see things like:

`[Log - 3:38:46 PM] Execute linting: python -m doc8.main c:\Users\tilli\Documents\Visual Studio 2017\Projects\AutofacDocumentation\docs\advanced\debugging.rst --config "c:\Users\tilli\Documents\Visual Studio 2017\Projects\AutofacDocumentation\doc8.ini" in c:\Users\tilli\Documents\Visual Studio 2017\Projects\AutofacDocumentation.`

My `settings.json` required that I add quotes around the `doc8.ini` location:

```json
{
  "restructuredtext.builtDocumentationPath": "${workspaceRoot}\\docs\\_build\\html",
  "restructuredtext.confPath": "${workspaceFolder}\\docs",
  "restructuredtext.linter.extraArgs": [
    "--config",
    "\"${workspaceFolder}\\doc8.ini\""
  ]
}
```

However, the location of the actual file being linted is not quoted, so if I take the command line...

`python -m doc8.main c:\Users\tilli\Documents\Visual Studio 2017\Projects\AutofacDocumentation\docs\advanced\debugging.rst --config "c:\Users\tilli\Documents\Visual Studio 2017\Projects\AutofacDocumentation\doc8.ini"`

...and run that, it fails.

```
C:\Python37\lib\site-packages\doc8\main.py:90: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  parser.readfp(fh, filename=fn)
Scanning...
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\lib\site-packages\doc8\main.py", line 382, in <module>
    sys.exit(main())
  File "C:\Python37\lib\site-packages\doc8\main.py", line 359, in main
    files, files_ignored = scan(args)
  File "C:\Python37\lib\site-packages\doc8\main.py", line 188, in scan
    for filename, ignoreable in file_iter:
  File "C:\Python37\lib\site-packages\doc8\utils.py", line 58, in find_files
    raise IOError('Invalid path: %s' % path)
OSError: Invalid path: c:\Users\tilli\Documents\Visual
```

If I manually add quotes, it works.

`python -m doc8.main "c:\Users\tilli\Documents\Visual Studio 2017\Projects\AutofacDocumentation\docs\advanced\debugging.rst" --config "c:\Users\tilli\Documents\Visual Studio 2017\Projects\AutofacDocumentation\doc8.ini"`

```
C:\Python37\lib\site-packages\doc8\main.py:90: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  parser.readfp(fh, filename=fn)
Scanning...
Validating...
c:\Users\tilli\Documents\Visual Studio 2017\Projects\AutofacDocumentation\docs\contributors.rst:2: D001 Line too long
c:\Users\tilli\Documents\Visual Studio 2017\Projects\AutofacDocumentation\docs\contributors.rst:7: D005 No newline at end of file
========
Total files scanned = 1
Total files ignored = 0
Total accumulated errors = 2
Detailed error counts:
    - CheckCarriageReturn = 0
    - CheckIndentationNoTab = 0
    - CheckMaxLineLength = 1
    - CheckNewlineEndOfFile = 1
    - CheckTrailingWhitespace = 0
    - CheckValidity = 0
```

I think the execution bit just needs to be updated to quote the path to the target file.

**Comment by tillig** [comment]
[I think that happens here.](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/9a28817d33dabb4376f97523d96f6224a2b7212c/src/features/utils/lintingProvider.ts#L158)
