### ISSUE TITLE
Preview of single file runs with python->python2

### ISSUE THREAD

**Issue by memeplex** [vscode-restructuredtext/vscode-restructuredtext#178]
**Environment**
- Extension version: 114.0.0
- Visual Studio Code version: 1.38.1
- Operating System version: Ubuntu 19.04
- Python version: 3.7.3
- sphinx version: 2.2.0
- A sample of conf.py or its important fragments: no conf.py

**Expected behavior**

Preview works well even for files outside a workspace folder and in systems where python is linked to python2.

**Actual behavior**

I create a `/tmp/test.rst` file and open the preview for it. In the reStructuredTest output panel I get:

```
Error: Command failed:  "/home/carlos/.vscode/extensions/lextudio.restructuredtext-114.0.0/python/preview.py" "/tmp/test.rst"
from: can't read /var/mail/__future__
from: can't read /var/mail/docutils
/home/carlos/.vscode/extensions/lextudio.restructuredtext-114.0.0/python/preview.py: 9: /home/carlos/.vscode/extensions/lextudio.restructuredtext-114.0.0/python/preview.py: Syntax error: "(" unexpected (expecting "then")

	at ChildProcess.exithandler (child_process.js:299:12)
	at ChildProcess.emit (events.js:182:13)
	at maybeClose (internal/child_process.js:962:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

Adding a `#!/bin/python3` shebang to preview.py fixes the issue.

Of course, python is still python2 in most linux distributions (except for arch based ones, AFAIK).

**Detailed Steps to reproduce the problem**

* Create `/tmp/test.rst`
* Open the preview window for it
* Check the output log

**Comment by lextm** [comment]
It cannot be reproduced on macOS 10.14.6 with Python 3.7.0, so I will try a Linux machine later.

**Comment by memeplex** [comment]
Ok, I think this is because you're using `pythonPath` in python.js. It's fine but maybe it should be documented as a FAQ or something because in most linux distributions python is still linked to python2 (see [PEP 394](https://www.python.org/dev/peps/pep-0394/)). And vscode users don't usually deal with `pythonPath` AFAIK because the python extension allows to toggle the current interpreter in more powerful ways.

**Comment by lextm** [comment]
The documentation does ask users to choose a specific Python build, https://docs.restructuredtext.net/articles/configuration.html#sample-project

**Comment by ssbarnea** [comment]
I am facing the same bug while I do have the python path configured correctly. Still getting lots of errors:
```
[Log - 11:57:02 AM] Compiling file: /Users/ssbarnea/c/os/selinux/README.rst
[Log - 11:57:02 AM] Running cmd: undefined "/Users/ssbarnea/.vscode-insiders/extensions/lextudio.restructuredtext-116.0.0/python/preview.py" "/Users/ssbarnea/c/os/selinux/README.rst"
[Log - 11:57:19 AM] Execute linting: /Users/ssbarnea/.pyenv/shims/doc8 "/Users/ssbarnea/c/os/selinux/README.rst" in undefined.
[Log - 11:57:19 AM] Execute linting: /Users/ssbarnea/.pyenv/shims/doc8 "/Users/ssbarnea/c/os/selinux/README.rst" in undefined.
[Log - 11:57:20 AM] Execute linting: /Users/ssbarnea/.pyenv/shims/doc8 "/Users/ssbarnea/c/os/selinux/README.rst" in undefined.
[Log - 11:57:22 AM] provideTextDocumentContent
{
  "source": "file:///Users/ssbarnea/c/os/selinux/README.rst",
  "line": 0,
  "lineCount": 33,
  "scrollPreviewWithEditor": true,
  "scrollEditorWithPreview": true,
  "doubleClickToSwitchToEditor": true,
  "disableSecurityWarnings": false
}
[Log - 11:57:22 AM] Compiling file: /Users/ssbarnea/c/os/selinux/README.rst
[Log - 11:57:22 AM] Running cmd: undefined "/Users/ssbarnea/.vscode-insiders/extensions/lextudio.restructuredtext-116.0.0/python/preview.py" "/Users/ssbarnea/c/os/selinux/README.rst"
[Log - 11:57:22 AM] Error
Command failed:  "/Users/ssbarnea/.vscode-insiders/extensions/lextudio.restructuredtext-116.0.0/python/preview.py" "/Users/ssbarnea/c/os/selinux/README.rst"
from: can't read /var/mail/__future__
import: unable to grab mouse `': No such file or directory @ error/xwindow.c/XSelectWindow/9188.
import: unable to grab mouse `': No such file or directory @ error/xwindow.c/XSelectWindow/9188.
import: unable to grab mouse `': No such file or directory @ error/xwindow.c/XSelectWindow/9188.
from: can't read /var/mail/docutils
/Users/ssbarnea/.vscode-insiders/extensions/lextudio.restructuredtext-116.0.0/python/preview.py: line 9: syntax error near unexpected token `('
/Users/ssbarnea/.vscode-insiders/extensions/lextudio.restructuredtext-116.0.0/python/preview.py: line 9: `if sys.version_info >= (3,):'
```
