### ISSUE TITLE
ModuleNotFoundError: No module named 'guzzle_sphinx_theme'

### ISSUE THREAD

**Issue by AndreyNikiforov** [vscode-restructuredtext/vscode-restructuredtext#240]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: v129.0.0
- [x] Visual Studio Code version: 
Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
- [ ] Operating System version:
- [ ] Python version:
- [ ] sphinx version:
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

Clean/default/happy_path Install should give a working version of the product

**Actual behavior**
```
Cannot show preview page.
Description:
Cannot generate preview page.

Possible causes are,

Python is not installed properly.
Sphinx is not installed properly (if preview uses "conf.py").
Wrong value is set on "restructuredtext.sphinxBuildPath".
A wrong "conf.py" file is selected.
DocUtils is not installed properly (if preview uses docutils).
Detailed error message
Error
Command failed: "python" -m sphinx -b html . "c:\src\RxPY\docs\_build\html"

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\Users\We\AppData\Local\Programs\Python\Python38\lib\site-packages\sphinx\config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "C:\Users\We\AppData\Local\Programs\Python\Python38\lib\site-packages\sphinx\util\pycompat.py", line 89, in execfile_
    exec(code, _globals)
  File "c:\src\RxPY\docs\conf.py", line 18, in 
    import guzzle_sphinx_theme
ModuleNotFoundError: No module named 'guzzle_sphinx_theme'


Error: Command failed: "python" -m sphinx -b html . "c:\src\RxPY\docs\_build\html"

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\Users\We\AppData\Local\Programs\Python\Python38\lib\site-packages\sphinx\config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "C:\Users\We\AppData\Local\Programs\Python\Python38\lib\site-packages\sphinx\util\pycompat.py", line 89, in execfile_
    exec(code, _globals)
  File "c:\src\RxPY\docs\conf.py", line 18, in 
    import guzzle_sphinx_theme
ModuleNotFoundError: No module named 'guzzle_sphinx_theme'


	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\Users\We\AppData\Local\Programs\Python\Python38\lib\site-packages\sphinx\config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "C:\Users\We\AppData\Local\Programs\Python\Python38\lib\site-packages\sphinx\util\pycompat.py", line 89, in execfile_
    exec(code, _globals)
  File "c:\src\RxPY\docs\conf.py", line 18, in 
    import guzzle_sphinx_theme
ModuleNotFoundError: No module named 'guzzle_sphinx_theme'

More Information
Diagnostics information has been written to OUTPUT | reStructuredText panel.

The troubleshooting guide can be found at

https://docs.restructuredtext.net/articles/troubleshooting.html
```

**Detailed Steps to reproduce the problem**
- Open VSC with project that has .rst file
- Open extensions and install this extension
- Open .rst file
- Select "reStructuredtext: Open preview on the Side" from "Command Pallete"
- Answer 'Install' in notification dialog about missing Sphynx
- Answer 'Install' in notification dialog about missing rstcheck

**Comment by lextm** [comment]
Your project uses the theme `guzzle_sphinx_theme`, so you have to run `pip install guzzle_sphinx_theme`. Not an issue of this extension.
