### ISSUE TITLE
Crash on type

### ISSUE THREAD

**Issue by cglacet** [vscode-restructuredtext/vscode-restructuredtext#276]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: v143.0.0
- [x] Visual Studio Code version: Version: 1.53.2
- [x] Operating System version: osx 11.2.1
- [x] Python version: Python 3.8.2
- [x] sphinx version: 3.5.1
- [x] A sample of conf.py or its important fragments: included at the end

**How it occurs**

Every time I type a character in a vscode `.rst` file the extension crashes.

**Output**

```bash
INFO:snooty.main:Snooty 1.8.7.dev0 starting
INFO:snooty.language_server:Started
WARNING:pyls_jsonrpc.endpoint:Ignoring notification for unknown method workspace/didChangeConfiguration
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 1
Traceback (most recent call last):
  File "/Users/cglacet/.pyenv/versions/kune-documentation/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/Users/cglacet/.pyenv/versions/kune-documentation/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/Users/cglacet/.pyenv/versions/kune-documentation/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/Users/cglacet/.pyenv/versions/kune-documentation/lib/python3.8/site-packages/snooty/language_server.py", line 450, in m_text_document__completion
    return self.completions(textDocument.uri, position)
AttributeError: 'dict' object has no attribute 'uri'
[Error - 7:34:42 AM] Request textDocument/completion failed.
  Message: AttributeError: 'dict' object has no attribute 'uri'
  Code: -32602 
[object Object]
```

**Sphinx conf.py**

In my conf file I have 2 patches to correct bugs I had, the rest of it is pretty standard. Here are the two patches:

```python
"""Patching m2r2"""
import m2r2

current_m2r2_setup = m2r2.setup


def patched_m2r2_setup(app):
    try:
        return current_m2r2_setup(app)
    except (AttributeError):
        app.add_source_suffix(".md", "markdown")
        app.add_source_parser(m2r2.M2RParser)
    return dict(
        version=m2r2.__version__,
        parallel_read_safe=True,
        parallel_write_safe=True,
    )


m2r2.setup = patched_m2r2_setup

"""Patching sphinx titles"""
from docutils import nodes
from sphinx.application import Sphinx
from sphinx.environment.collectors.title import TitleCollector

_process_doc = TitleCollector.process_doc


def process_doc(self, app: Sphinx, doctree: nodes.document) -> None:
    if doctree.traverse(nodes.section):
        _process_doc(self, app, doctree)
    else:
        titlenode = nodes.title()
        app.env.titles[app.env.docname] = titlenode
        app.env.longtitles[app.env.docname] = titlenode


TitleCollector.process_doc = process_doc
```

**Comment by bondezbond** [comment]
Curious on the issue. I"m having a similar issue on vscode syntax highlighting works but it throws that error when I start typing.

Extension version v143.0.0
Visual Studio Code version: Version: 1.53.2 Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4 
Operating System version: OSX 11.2.1
Python Version: 3.9.0
sphinx version: 3.5.1
