### ISSUE TITLE
IndexError: list index out of range, when adding new .rst file before adding to index.rst

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#280]
@David-Cowan
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 144.0.0
- [ ] Visual Studio Code version:  1.53.2
- [ ] Operating System version: Ubuntu 20.4
- [ ] Python version: 3.8
- [ ] sphinx version: 4.0
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

No exception

**Actual behavior**

```
Traceback (most recent call last):
  File "xxx/.tox/py3/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "xxx/.tox/py3/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "xxx/.tox/py3/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "xxx/.tox/py3/lib/python3.8/site-packages/snooty/language_server.py", line 450, in m_text_document__completion
    return self.completions(textDocument["uri"], position)
  File "xxx/.tox/py3/lib/python3.8/site-packages/snooty/language_server.py", line 418, in completions
    line_content = self.project.get_line_content(filePath, position["line"])
  File "xxx/.tox/py3/lib/python3.8/site-packages/snooty/parser.py", line 1530, in get_line_content
    return self._project.get_line_content(path, line)
  File "xxx/.tox/py3/lib/python3.8/site-packages/snooty/parser.py", line 1219, in get_line_content
    return lines[line]
IndexError: list index out of range
[Error - 11:18:07 AM] Request textDocument/completion failed.
  Message: IndexError: list index out of range
  Code: -32602 
[object Object]

```

**Detailed Steps to reproduce the problem**

If I have a document with an index.rst and then add new blah.rst file, then I get the exception.

The workaround is to add blah.rst to index.rst.

**Comment by oharboe** [comment]
```
.tox/py3/bin/python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import snooty
>>> snooty.__version__
'1.8.9.dev0'
>>> 
```

**Comment by lextm** [comment]
Duplicate to https://github.com/vscode-restructuredtext/snooty-parser/issues/20
