### ISSUE TITLE
Couldn't start client Snooty Language Client

### ISSUE THREAD

**Issue by lextm** [vscode-restructuredtext/vscode-restructuredtext#302]
OUTPUT: reStructuredText 
```
[Log - 02:09:09] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 02:09:09] OS is win32
[Log - 02:09:09] Running cmd: "python" -c "import sys; print(sys.version_info[0])"
[Log - 02:09:09] Successful exec
[Log - 02:09:09] Running cmd: "python" -c "import platform; from distutils.version import LooseVersion; print(LooseVersion(platform.python_version()) < LooseVersion('3.7.0'))"
[Log - 02:09:09] Successful exec
[Log - 02:09:09] Running cmd: "python" -c "import snooty; from distutils.version import LooseVersion; print(LooseVersion(snooty.__version__) < LooseVersion('1.9.1'))"
[Log - 02:09:09] Successful exec
[Log - 02:09:09] Use Snooty language server
```

OUTPUT: Snooty Language Client
```
INFO:snooty.main:Snooty 1.9.1.dev0 starting
INFO:snooty.language_server:Started
INFO:snooty.parser:git error getting branch name: fatal: not a git repository (or any of the parent directories): .git
```

And finally NOTIFICATION:
`Couldn't start client Snooty Language Client`
Source: reStructuredText (Extension)

_Originally posted by @DmitrySokolov in https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/283#issuecomment-840154011_

**Comment by DmitrySokolov** [comment]
Logs for the new version:

```
INFO:snooty.main:Snooty 1.9.2.dev0 starting
INFO:snooty.language_server:Started
INFO:snooty.parser:git error getting branch name: fatal: not a git repository (or any of the parent directories): .git

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Dev\Tools\Python3\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Dev\Tools\Python3\lib\site-packages\watchdog\observers\api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "C:\Dev\Tools\Python3\lib\site-packages\watchdog\observers\api.py", line 372, in dispatch_events
    handler.dispatch(event)
  File "C:\Dev\Tools\Python3\lib\site-packages\snooty\util.py", line 166, in dispatch
WARNING:pyls_jsonrpc.endpoint:Ignoring notification for unknown method workspace/didChangeConfiguration
    self.on_event(event)
  File "C:\Dev\Tools\Python3\lib\site-packages\snooty\parser.py", line 1589, in _on_asset_event
    self._project.on_asset_event(ev)
  File "C:\Dev\Tools\Python3\lib\site-packages\snooty\parser.py", line 1520, in on_asset_event
    self.update(self.pages[page_id].source_path)
  File "C:\Dev\Tools\Python3\lib\site-packages\snooty\parser.py", line 1085, in __getitem__
    assert not self.__changed_pages
AssertionError
```

**Comment by DmitrySokolov** [comment]
The next launch:
```
INFO:snooty.main:Snooty 1.9.2.dev0 starting
INFO:snooty.language_server:Started
INFO:snooty.parser:git error getting branch name: fatal: not a git repository (or any of the parent directories): .git

WARNING:pyls_jsonrpc.endpoint:Ignoring notification for unknown method workspace/didChangeConfiguration
```

**Comment by lextm** [comment]
"INFO:snooty.parser:git error getting branch name: fatal: not a git repository (or any of the parent directories): .git" is expected. Snooty was designed for MongoDB internal documentation system where all doc projects are saved in Git, so it naturally tries to read .git folder when analyzing a folder.

If "Couldn't start client Snooty Language Client" or  "AssertionError" cannot be reliably reproduced, I don't think more effort can be spent on this issue.

**Comment by DmitrySokolov** [comment]
So, is it working when no asserts or errors in the Output?

I've got the `snooty: idle` on the status bar.

**Comment by DmitrySokolov** [comment]
I see this asserts only after restarting from Windows Hibernation mode.

**Comment by lextm** [comment]
Finally experienced this issue, but the call stacks do not help much.
```
workbench.desktop.main.js:749 FileNotFoundError: [WinError 2] The system cannot find the file specified
onDidChangeNotification @ workbench.desktop.main.js:749
(anonymous) @ workbench.desktop.main.js:749
fire @ workbench.desktop.main.js:60
addNotification @ workbench.desktop.main.js:751
notify @ workbench.desktop.main.js:1587
(anonymous) @ workbench.desktop.main.js:1542
_showMessage @ workbench.desktop.main.js:1542
$showMessage @ workbench.desktop.main.js:1542
_doInvokeHandler @ workbench.desktop.main.js:1549
_invokeHandler @ workbench.desktop.main.js:1549
_receiveRequest @ workbench.desktop.main.js:1549
_receiveOneMessage @ workbench.desktop.main.js:1549
(anonymous) @ workbench.desktop.main.js:1549
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
T @ workbench.desktop.main.js:2897
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
workbench.desktop.main.js:749 Couldn't start client Snooty Language Client
onDidChangeNotification @ workbench.desktop.main.js:749
(anonymous) @ workbench.desktop.main.js:749
fire @ workbench.desktop.main.js:60
addNotification @ workbench.desktop.main.js:751
notify @ workbench.desktop.main.js:1587
(anonymous) @ workbench.desktop.main.js:1542
_showMessage @ workbench.desktop.main.js:1542
$showMessage @ workbench.desktop.main.js:1542
_doInvokeHandler @ workbench.desktop.main.js:1549
_invokeHandler @ workbench.desktop.main.js:1549
_receiveRequest @ workbench.desktop.main.js:1549
_receiveOneMessage @ workbench.desktop.main.js:1549
(anonymous) @ workbench.desktop.main.js:1549
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
T @ workbench.desktop.main.js:2897
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
workbench.desktop.main.js:62 [Extension Host] rejected promise not handled within 1 second: Error: FileNotFoundError: [WinError 2] The system cannot find the file specified
S @ workbench.desktop.main.js:62
$logExtensionHostMessage @ workbench.desktop.main.js:1549
_doInvokeHandler @ workbench.desktop.main.js:1549
_invokeHandler @ workbench.desktop.main.js:1549
_receiveRequest @ workbench.desktop.main.js:1549
_receiveOneMessage @ workbench.desktop.main.js:1549
(anonymous) @ workbench.desktop.main.js:1549
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
T @ workbench.desktop.main.js:2897
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
workbench.desktop.main.js:62 [Extension Host] stack trace: Error: FileNotFoundError: [WinError 2] The system cannot find the file specified	at handleResponse (c:\Users\lextm\.vscode\extensions\lextudio.restructuredtext-160.0.0\node_modules\vscode-jsonrpc\lib\main.js:449:48)	at processMessageQueue (c:\Users\lextm\.vscode\extensions\lextudio.restructuredtext-160.0.0\node_modules\vscode-jsonrpc\lib\main.js:276:17)	at Immediate.<anonymous> (c:\Users\lextm\.vscode\extensions\lextudio.restructuredtext-160.0.0\node_modules\vscode-jsonrpc\lib\main.js:260:13)	at processImmediate (internal/timers.js:461:21)
S @ workbench.desktop.main.js:62
$logExtensionHostMessage @ workbench.desktop.main.js:1549
_doInvokeHandler @ workbench.desktop.main.js:1549
_invokeHandler @ workbench.desktop.main.js:1549
_receiveRequest @ workbench.desktop.main.js:1549
_receiveOneMessage @ workbench.desktop.main.js:1549
(anonymous) @ workbench.desktop.main.js:1549
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
T @ workbench.desktop.main.js:2897
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
workbench.desktop.main.js:2036 [[object Object]]FileNotFoundError: [WinError 2] The system cannot find the file specified
$onExtensionRuntimeError @ workbench.desktop.main.js:2036
_doInvokeHandler @ workbench.desktop.main.js:1549
_invokeHandler @ workbench.desktop.main.js:1549
_receiveRequest @ workbench.desktop.main.js:1549
_receiveOneMessage @ workbench.desktop.main.js:1549
(anonymous) @ workbench.desktop.main.js:1549
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
T @ workbench.desktop.main.js:2897
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
workbench.desktop.main.js:2036 Error: FileNotFoundError: [WinError 2] The system cannot find the file specified
	at handleResponse (c:\Users\lextm\.vscode\extensions\lextudio.restructuredtext-160.0.0\node_modules\vscode-jsonrpc\lib\main.js:449:48)
	at processMessageQueue (c:\Users\lextm\.vscode\extensions\lextudio.restructuredtext-160.0.0\node_modules\vscode-jsonrpc\lib\main.js:276:17)
	at Immediate.<anonymous> (c:\Users\lextm\.vscode\extensions\lextudio.restructuredtext-160.0.0\node_modules\vscode-jsonrpc\lib\main.js:260:13)
	at processImmediate (internal/timers.js:461:21)
```

and in my case, Windows reboot does not help resolve it.
