### ISSUE TITLE
Can't preview the .rst file

### ISSUE THREAD

**Issue by borisliu** [vscode-restructuredtext/vscode-restructuredtext#32]
Please provide the following information,

**Environment**
- [x] Extension version:0.0.19
- [x] Visual Studio Code version:1.8.1
- [x] Operating System version:Windows 10
- [x] Python version:Python 3.5
- [x] sphinx version:1.5.1
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
Preview the .rst file

**Actual behavior**
无法打开“Preview 'README.rst'”: Error

**Detailed Steps to reproduce the problem**
workbench.main.js:94 无法打开“Preview 'README.rst'”: Error
Command failed: make html

Error: Command failed: make html

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

。: Error: 无法打开“Preview 'README.rst'”: Error
Command failed: make html

Error: Command failed: make html

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

。
    at t.doHandleSetInputError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:3539)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:3145
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:18898)
    at t.doSetInput (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:2891)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:770
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:19522)
    at t.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:742)
    at t.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:19)
    at e.doOpenEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:114:308)
    at e.openEditor (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:113:31760)

**Comment by lextm** [comment]
Do you have conf.py and makefile in the same folder?

**Comment by borisliu** [comment]
No. You can see my attachment.
![2017-01-08 7 53 13](https://cloud.githubusercontent.com/assets/2763183/21746179/c41e3dc8-d577-11e6-9455-4a701586fd39.png)

**Comment by lextm** [comment]
I will soon update the guide.

The cause is that you did not start from a sample project created by `sphinx-quickstart`,

http://www.sphinx-doc.org/en/1.5.1/tutorial.html

Then this folder misses a few essential files (such as makefile/make.bat) required by this extension to provide live preview (that's what the error message asks for).

So you might try to follow the tutorial and take a look at the recommended folder structure. (Don't use separate source and build folders though.)
