### ISSUE TITLE
[Bug]: cannot preview rst files

### ISSUE THREAD

**Issue by CollieIsCute** [vscode-restructuredtext/vscode-restructuredtext#321]
### Expected behavior

I am a newbie to rst files. I install everything I knew ([in the website](https://docs.restructuredtext.net/articles/prerequisites.html))I expect vscode can produce the live preview, but it didn't.

![image](https://user-images.githubusercontent.com/43088530/132136569-223c0131-4040-4177-aef3-0ce54b61dfb2.png)

### Actual behavior

it stopped and produce a log.

### Detailed steps

I've add the sphinx-build path to vscode settings
![image](https://user-images.githubusercontent.com/43088530/132136635-e948ce5d-5ad1-4219-b13c-a1027c9d7130.png)

I don't know how to fix this. Does anyone know what's wrong?

### Extension information

v163.0.0

### Visual Studio Code information

1.60.0 e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff x64 (sphinx_2.4.4)

### Operating system information

OS: Arch Linux x86_64, Kernel: 5.13.13-arch1-1

### Python information

Python 3.9.6

### Sphinx information

sphinx_2.4.4

### Contents of conf.py

```python
# -*- coding: utf-8 -*-
#
# The Linux Kernel documentation build configuration file, created by
# sphinx-quickstart on Fri Feb 12 13:51:46 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import sphinx

# Get Sphinx version
major, minor, patch = sphinx.version_info[:3]


# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('sphinx'))
from load_config import loadConfig

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '1.7'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['kerneldoc', 'rstFlatTable', 'kernel_include',
              'kfigure', 'sphinx.ext.ifconfig', 'automarkup',
              'maintainers_include', 'sphinx.ext.autosectionlabel',
              'kernel_abi', 'kernel_feat']

if major >= 3:
    if (major > 3) or (minor > 0 or patch >= 2):
        # Sphinx c function parser is more pedantic with regards to type
        # checking. Due to that, having macros at c:function cause problems.
        # Those needed to be scaped by using c_id_attributes[] array
        c_id_attributes = [
            # GCC Compiler types not parsed by Sphinx:
            "__restrict__",

            # include/linux/compiler_types.h:
            "__iomem",
            "__kernel",
            "noinstr",
            "notrace",
            "__percpu",
            "__rcu",
            "__user",

            # include/linux/compiler_attributes.h:
            "__alias",
            "__aligned",
            "__aligned_largest",
            "__always_inline",
            "__assume_aligned",
            "__cold",
            "__attribute_const__",
            "__copy",
            "__pure",
            "__designated_init",
            "__visible",
            "__printf",
            "__scanf",
            "__gnu_inline",
            "__malloc",
            "__mode",
            "__no_caller_saved_registers",
            "__noclone",
            "__nonstring",
            "__noreturn",
            "__packed",
            "__pure",
            "__section",
            "__always_unused",
            "__maybe_unused",
            "__used",
            "__weak",
            "noinline",

            # include/linux/memblock.h:
            "__init_memblock",
            "__meminit",

            # include/linux/init.h:
            "__init",
            "__ref",

            # include/linux/linkage.h:
            "asmlinkage",
        ]

else:
    extensions.append('cdomain')

# Ensure that autosectionlabel will produce unique names
autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = 2

extensions.append("sphinx.ext.imgmath")

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'The Linux Kernel'
copyright = 'The kernel development community'
author = 'The kernel development community'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# In a normal build, version and release are are set to KERNELVERSION and
# KERNELRELEASE, respectively, from the Makefile via Sphinx command line
# arguments.
#
# The following code tries to extract the information by reading the Makefile,
# when Sphinx is run directly (e.g. by Read the Docs).
try:
    makefile_version = None
    makefile_patchlevel = None
    for line in open('../Makefile'):
        key, val = [x.strip() for x in line.split('=', 2)]
        if key == 'VERSION':
            makefile_version = val
        elif key == 'PATCHLEVEL':
            makefile_patchlevel = val
        if makefile_version and makefile_patchlevel:
            break
except:
    pass
finally:
    if makefile_version and makefile_patchlevel:
        version = release = makefile_version + '.' + makefile_patchlevel
    else:
        version = release = "unknown version"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['output']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

primary_domain = 'c'
highlight_language = 'none'

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

# The Read the Docs theme is available from
# - https://github.com/snide/sphinx_rtd_theme
# - https://pypi.python.org/pypi/sphinx_rtd_theme
# - python-sphinx-rtd-theme package (on Debian)
try:
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
except ImportError:
    sys.stderr.write('Warning: The Sphinx \'sphinx_rtd_theme\' HTML theme was not found. Make sure you have the theme installed to produce pretty HTML output. Falling back to the default theme.\n')

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".

html_static_path = ['sphinx-static']

html_context = {
    'css_files': [
        '_static/theme_overrides.css',
    ],
}

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
html_use_smartypants = False

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'h', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'r', 'sv', 'tr'
#html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'TheLinuxKerneldoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '11pt',

    # Latex figure (float) alignment
    #'figure_align': 'htbp',

    # Don't mangle with UTF-8 chars
    'inputenc': '',
    'utf8extra': '',

    # Set document margins
    'sphinxsetup': '''
        hmargin=0.5in, vmargin=1in,
        parsedliteralwraps=true,
        verbatimhintsturnover=false,
    ''',

    # For CJK One-half spacing, need to be in front of hyperref
    'extrapackages': r'\usepackage{setspace}',

    # Additional stuff for the LaTeX preamble.
    'preamble': '''
	% Prevent column squeezing of tabulary.
	\\setlength{\\tymin}{20em}
        % Use some font with UTF-8 support with XeLaTeX
        \\usepackage{fontspec}
        \\setsansfont{DejaVu Sans}
        \\setromanfont{DejaVu Serif}
        \\setmonofont{DejaVu Sans Mono}
     ''',
}

# Translations have Asian (CJK) characters which are only displayed if
# xeCJK is used

latex_elements['preamble']  += '''
    \\IfFontExistsTF{Noto Sans CJK SC}{
	% This is needed for translations
	\\usepackage{xeCJK}
	\\IfFontExistsTF{Noto Serif CJK SC}{
	    \\setCJKmainfont{Noto Serif CJK SC}[AutoFakeSlant]
	}{
	    \\setCJKmainfont{Noto Sans CJK SC}[AutoFakeSlant]
	}
	\\setCJKsansfont{Noto Sans CJK SC}[AutoFakeSlant]
	\\setCJKmonofont{Noto Sans Mono CJK SC}[AutoFakeSlant]
	% CJK Language-specific font choices
	\\IfFontExistsTF{Noto Serif CJK SC}{
	    \\newCJKfontfamily[SCmain]\\scmain{Noto Serif CJK SC}[AutoFakeSlant]
	    \\newCJKfontfamily[SCserif]\\scserif{Noto Serif CJK SC}[AutoFakeSlant]
	}{
	    \\newCJKfontfamily[SCmain]\\scmain{Noto Sans CJK SC}[AutoFakeSlant]
	    \\newCJKfontfamily[SCserif]\\scserif{Noto Sans CJK SC}[AutoFakeSlant]
	}
	\\newCJKfontfamily[SCsans]\\scsans{Noto Sans CJK SC}[AutoFakeSlant]
	\\newCJKfontfamily[SCmono]\\scmono{Noto Sans Mono CJK SC}[AutoFakeSlant]
	\\IfFontExistsTF{Noto Serif CJK TC}{
	    \\newCJKfontfamily[TCmain]\\tcmain{Noto Serif CJK TC}[AutoFakeSlant]
	    \\newCJKfontfamily[TCserif]\\tcserif{Noto Serif CJK TC}[AutoFakeSlant]
	}{
	    \\newCJKfontfamily[TCmain]\\tcmain{Noto Sans CJK TC}[AutoFakeSlant]
	    \\newCJKfontfamily[TCserif]\\tcserif{Noto Sans CJK TC}[AutoFakeSlant]
	}
	\\newCJKfontfamily[TCsans]\\tcsans{Noto Sans CJK TC}[AutoFakeSlant]
	\\newCJKfontfamily[TCmono]\\tcmono{Noto Sans Mono CJK TC}[AutoFakeSlant]
	\\IfFontExistsTF{Noto Serif CJK KR}{
	    \\newCJKfontfamily[KRmain]\\krmain{Noto Serif CJK KR}[AutoFakeSlant]
	    \\newCJKfontfamily[KRserif]\\krserif{Noto Serif CJK KR}[AutoFakeSlant]
	}{
	    \\newCJKfontfamily[KRmain]\\krmain{Noto Sans CJK KR}[AutoFakeSlant]
	    \\newCJKfontfamily[KRserif]\\krserif{Noto Sans CJK KR}[AutoFakeSlant]
	}
	\\newCJKfontfamily[KRsans]\\krsans{Noto Sans CJK KR}[AutoFakeSlant]
	\\newCJKfontfamily[KRmono]\\krmono{Noto Sans Mono CJK KR}[AutoFakeSlant]
	\\IfFontExistsTF{Noto Serif CJK JP}{
	    \\newCJKfontfamily[JPmain]\\jpmain{Noto Serif CJK JP}[AutoFakeSlant]
	    \\newCJKfontfamily[JPserif]\\jpserif{Noto Serif CJK JP}[AutoFakeSlant]
	}{
	    \\newCJKfontfamily[JPmain]\\jpmain{Noto Sans CJK JP}[AutoFakeSlant]
	    \\newCJKfontfamily[JPserif]\\jpserif{Noto Sans CJK JP}[AutoFakeSlant]
	}
	\\newCJKfontfamily[JPsans]\\jpsans{Noto Sans CJK JP}[AutoFakeSlant]
	\\newCJKfontfamily[JPmono]\\jpmono{Noto Sans Mono CJK JP}[AutoFakeSlant]
	% Dummy commands for Sphinx < 2.3 (no 'extrapackages' support)
	\\providecommand{\\onehalfspacing}{}
	\\providecommand{\\singlespacing}{}
	% Define custom macros to on/off CJK
	\\newcommand{\\kerneldocCJKon}{\\makexeCJKactive\\onehalfspacing}
	\\newcommand{\\kerneldocCJKoff}{\\makexeCJKinactive\\singlespacing}
	\\newcommand{\\kerneldocBeginSC}{%
	    \\begingroup%
	    \\scmain%
	}
	\\newcommand{\\kerneldocEndSC}{\\endgroup}
	\\newcommand{\\kerneldocBeginTC}{%
	    \\begingroup%
	    \\tcmain%
	    \\renewcommand{\\CJKrmdefault}{TCserif}%
	    \\renewcommand{\\CJKsfdefault}{TCsans}%
	    \\renewcommand{\\CJKttdefault}{TCmono}%
	}
	\\newcommand{\\kerneldocEndTC}{\\endgroup}
	\\newcommand{\\kerneldocBeginKR}{%
	    \\begingroup%
	    \\xeCJKDeclareCharClass{HalfLeft}{`“,`‘}%
	    \\xeCJKDeclareCharClass{HalfRight}{`”,`’}%
	    \\krmain%
	    \\renewcommand{\\CJKrmdefault}{KRserif}%
	    \\renewcommand{\\CJKsfdefault}{KRsans}%
	    \\renewcommand{\\CJKttdefault}{KRmono}%
	    \\xeCJKsetup{CJKspace = true} % For inter-phrase space
	}
	\\newcommand{\\kerneldocEndKR}{\\endgroup}
	\\newcommand{\\kerneldocBeginJP}{%
	    \\begingroup%
	    \\xeCJKDeclareCharClass{HalfLeft}{`“,`‘}%
	    \\xeCJKDeclareCharClass{HalfRight}{`”,`’}%
	    \\jpmain%
	    \\renewcommand{\\CJKrmdefault}{JPserif}%
	    \\renewcommand{\\CJKsfdefault}{JPsans}%
	    \\renewcommand{\\CJKttdefault}{JPmono}%
	}
	\\newcommand{\\kerneldocEndJP}{\\endgroup}
	% Single spacing in literal blocks
	\\fvset{baselinestretch=1}
	% To customize \\sphinxtableofcontents
	\\usepackage{etoolbox}
	% Inactivate CJK after tableofcontents
	\\apptocmd{\\sphinxtableofcontents}{\\kerneldocCJKoff}{}{}
    }{ % No CJK font found
	% Custom macros to on/off CJK (Dummy)
	\\newcommand{\\kerneldocCJKon}{}
	\\newcommand{\\kerneldocCJKoff}{}
	\\newcommand{\\kerneldocBeginSC}{}
	\\newcommand{\\kerneldocEndSC}{}
	\\newcommand{\\kerneldocBeginTC}{}
	\\newcommand{\\kerneldocEndTC}{}
	\\newcommand{\\kerneldocBeginKR}{}
	\\newcommand{\\kerneldocEndKR}{}
	\\newcommand{\\kerneldocBeginSC}{}
	\\newcommand{\\kerneldocEndKR}{}
    }
'''

# Fix reference escape troubles with Sphinx 1.4.x
if major == 1:
    latex_elements['preamble']  += '\\renewcommand*{\\DUrole}[2]{ #2 }\n'

# With Sphinx 1.6, it is possible to change the Bg color directly
# by using:
#	\definecolor{sphinxnoteBgColor}{RGB}{204,255,255}
#	\definecolor{sphinxwarningBgColor}{RGB}{255,204,204}
#	\definecolor{sphinxattentionBgColor}{RGB}{255,255,204}
#	\definecolor{sphinximportantBgColor}{RGB}{192,255,204}
#
# However, it require to use sphinx heavy box with:
#
#	\renewenvironment{sphinxlightbox} {%
#		\\begin{sphinxheavybox}
#	}
#		\\end{sphinxheavybox}
#	}
#
# Unfortunately, the implementation is buggy: if a note is inside a
# table, it isn't displayed well. So, for now, let's use boring
# black and white notes.

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
# Sorted in alphabetical order
latex_documents = [
]

# Add all other index files from Documentation/ subdirectories
for fn in os.listdir('.'):
    doc = os.path.join(fn, "index")
    if os.path.exists(doc + ".rst"):
        has = False
        for l in latex_documents:
            if l[0] == doc:
                has = True
                break
        if not has:
            latex_documents.append((doc, fn + '.tex',
                                    'Linux %s Documentation' % fn.capitalize(),
                                    'The kernel development community',
                                    'manual'))

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'thelinuxkernel', 'The Linux Kernel Documentation',
     [author], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'TheLinuxKernel', 'The Linux Kernel Documentation',
     author, 'TheLinuxKernel', 'One line description of project.',
     'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The basename for the epub file. It defaults to the project name.
#epub_basename = project

# The HTML theme for the epub output. Since the default themes are not
# optimized for small screen space, using the same theme for HTML and epub
# output is usually not wise. This defaults to 'epub', a theme designed to save
# visual space.
#epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or 'en' if the language is not set.
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
#epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files that should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3

# Allow duplicate toc entries.
#epub_tocdup = True

# Choose between 'default' and 'includehidden'.
#epub_tocscope = 'default'

# Fix unsupported image types using the Pillow.
#epub_fix_images = False

# Scale large images.
#epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#epub_show_urls = 'inline'

# If false, no index is generated.
#epub_use_index = True

#=======
# rst2pdf
#
# Grouping the document tree into PDF files. List of tuples
# (source start file, target name, title, author, options).
#
# See the Sphinx chapter of https://ralsina.me/static/manual.pdf
#
# FIXME: Do not add the index file here; the result will be too big. Adding
# multiple PDF files here actually tries to get the cross-referencing right
# *between* PDF files.
pdf_documents = [
    ('kernel-documentation', u'Kernel', u'Kernel', u'J. Random Bozo'),
]

# kernel-doc extension configuration for running Sphinx directly (e.g. by Read
# the Docs). In a normal build, these are supplied from the Makefile via command
# line arguments.
kerneldoc_bin = '../scripts/kernel-doc'
kerneldoc_srctree = '..'

# ------------------------------------------------------------------------------
# Since loadConfig overwrites settings from the global namespace, it has to be
# the last statement in the conf.py file
# ------------------------------------------------------------------------------
loadConfig(globals())
```

### Relevant log output

```shell
the following text is a log msg.

# Sphinx version: 2.4.4
# Python version: 3.9.6 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.1
# Last messages:
#   reading sources... [  1%] admin-guide/LSM/SELinux
#   reading sources... [  1%] admin-guide/LSM/SafeSetID
#   reading sources... [  1%] admin-guide/LSM/Smack
#   reading sources... [  1%] admin-guide/LSM/Yama
#   reading sources... [  1%] admin-guide/LSM/apparmor
#   reading sources... [  1%] admin-guide/LSM/index
#   reading sources... [  1%] admin-guide/LSM/tomoyo
#   reading sources... [  1%] admin-guide/README
#   reading sources... [  1%] admin-guide/abi
#   reading sources... [  1%] admin-guide/abi-obsolete
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.4) from /home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/alabaster/__init__.py
#   kerneldoc (1.0) from /home/mst/syncfolder/linux/Documentation/sphinx/kerneldoc.py
#   rstFlatTable (1.0) from /home/mst/syncfolder/linux/Documentation/sphinx/rstFlatTable.py
#   kernel_include (1.0) from /home/mst/syncfolder/linux/Documentation/sphinx/kernel_include.py
#   kfigure (1.0.0) from /home/mst/syncfolder/linux/Documentation/sphinx/kfigure.py
#   sphinx.ext.ifconfig (2.4.4) from /home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/ext/ifconfig.py
#   automarkup (unknown version) from /home/mst/syncfolder/linux/Documentation/sphinx/automarkup.py
#   maintainers_include (1.0) from /home/mst/syncfolder/linux/Documentation/sphinx/maintainers_include.py
#   kernel_abi (1.0) from /home/mst/syncfolder/linux/Documentation/sphinx/kernel_abi.py
#   kernel_feat (1.0) from /home/mst/syncfolder/linux/Documentation/sphinx/kernel_feat.py
#   cdomain (1.1) from /home/mst/syncfolder/linux/Documentation/sphinx/cdomain.py
#   sphinx.ext.imgmath (2.4.4) from /home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/ext/imgmath.py
Traceback (most recent call last):
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/io.py", line 316, in read_doc
    pub.publish()
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/io.py", line 130, in read
    self.parse()
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/sphinx/parsers.py", line 93, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/home/mst/syncfolder/linux/sphinx_2.4.4/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/mst/syncfolder/linux/Documentation/sphinx/kernel_abi.py", line 89, in run
    srctree = path.abspath(os.environ["srctree"])
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'srctree'

```
```

**Comment by lextm** [comment]
When preview failed, it should have shown you an error page. What did it say?

Since your `conf.py` file points to `sphinx_rtd_theme`, you also need to run `pip install sphinx_rtd_theme` before opening up live preview (and the error page should tell you clearly that theme is missing).

**Comment by CornJojk** [comment]
Newly installed reStructuredText on VScode runnin as WSL:UBUNTU-20.04 remote. 
Preview displays this error message:

`TypeError: Cannot read property 'confPyDirectory' of undefined`

**Comment by lextm** [comment]
@CornJojk Please report new issue via https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/new/choose Don't post under someone else' report.

**Comment by CornJojk** [comment]
> @CornJojk Please report new issue via https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/new/choose Don't post under someone else' report.

So issues are the opposite of forums? one bug, many reports.

**Comment by lextm** [comment]
@CornJojk you didn't read through the whole thread to see that the initial report to learn its symptoms. Those symptoms were unique and have nothing to do with yours. That's why I asked you to open a new one and provide more details.

GitHub is clearly not a forum and "one bug, many reports" does not apply well here.
