### ISSUE TITLE
[Bug]: Preview does not work after upgrading to the latest extension

### ISSUE THREAD

**Issue by twodrops** [vscode-restructuredtext/vscode-restructuredtext#324]
### Expected behavior

The preview always worked before

### Actual behavior

The preview does not work anymore. On first startup of the preview, it throws the following exception in log and the preview if blank. See log below.
There after for each new preview, the preview window remains blank with no new exceptions.

### Detailed steps

I am using a Docker based Vscode DevContainer setup. The extension has always worked.

### Extension information

164.0.0

### Visual Studio Code information

1.60.0

### Operating system information

Windows 10 (with Vscode DevContainer)

### Python information

3.8.10

### Sphinx information

3.5.4

### Relevant log output

```shell
[renderer1] [error] Cannot read property 'resource' of undefined: TypeError: Cannot read property 'resource' of undefined
	at Function.revive (/home/dockeruser/.vscode-server/extensions/lextudio.restructuredtext-164.0.0/out/preview/preview.js:83:49)
	at RSTPreviewManager.deserializeWebviewPanel (/home/dockeruser/.vscode-server/extensions/lextudio.restructuredtext-164.0.0/out/preview/previewManager.js:64:52)
	at s.$deserializeWebviewPanel (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:95:84234)
	at i._doInvokeHandler (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:98:13543)
	at i._invokeHandler (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:98:13227)
	at i._receiveRequest (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:98:11889)
	at i._receiveOneMessage (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:98:10567)
	at /vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:98:8663
	at c.fire (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at l.fire (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:15781)
	at /vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:113:30187
	at c.fire (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at l.fire (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:15781)
	at r._receiveMessage (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:21051)
	at /vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:17929
	at c.fire (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at v.acceptChunk (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:13142)
	at /vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:12490
	at c.fire (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at E._acceptChunk (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:113:19362)
	at /vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:113:15775
	at Socket.w (/vscode/vscode-server/bin/x64/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:113:13350)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23)


The console output shows that the HTML preview to be shown is generated correctly.

[Log - 1:40:43 PM] Running cmd: "python" -c "import sphinx;"
[Log - 1:40:43 PM] Successful exec
[Log - 1:40:43 PM] [preview] Compiling file: /workspace/docs/mydoc.rst
[Log - 1:40:43 PM] [preview] Sphinx conf.py directory: /workspace
[Log - 1:40:43 PM] [preview] Sphinx html directory: /workspace/build/
[Log - 1:40:43 PM] [preview] Compiler: "python" -m sphinx -b html . "/workspace/build/"
[Log - 1:40:43 PM] [preview] Working directory: /workspace
[Log - 1:40:43 PM] [preview] HTML file: /workspace/build/mydoc.html
```

**Comment by twodrops** [comment]
Sorry, it is indeed working.
The incremental build is broken in my project and it was taking more than a minute to generate the HTML. This made me feel that the previewer is not working.

What confused me is that the extension prints out the following line in the console even before the html file is generated.
> [preview] HTML file: /workspace/build/mydoc.html

What would be nice is to show the above message once is build exists or show a 
> Successful exec

after the build is complete.

What do you think? Shall I raise a PR?

**Comment by lextm** [comment]
I added a more visible indicator in release 165.0.0, which you might try out.

When the preview engine is kicked out, the preview tab title will first change to `Preview is loading...`, and then `Preview xxx.rst`.

**Comment by lextm** [comment]
Moved the message from tab title to the status bar.
