### ISSUE TITLE
[Bug]: rstcheck cannot be installed by this plugin

### ISSUE THREAD

**Issue by danieltuzes** [vscode-restructuredtext/vscode-restructuredtext#353]
### Expected behavior

The plugin installs rstcheck successfully.

### Actual behavior

The plugin doesn't install it, fails, and provides a feedback: 
> Could not install rstcheck. Please run `pip install rstcheck` to use this extension, or check your Python path.

### Detailed steps

Install lexstudio's restructured text plugin, but don't install rstcheck. The plugin identifies that rstcheck is missing:

```
[Log - 22:15:13] Running cmd: "C:\Users\daniel\miniconda3\envs\docs\python.exe" -c "import rstcheck;"
[Log - 22:15:13] Error
Command failed: "C:\Users\daniel\miniconda3\envs\docs\python.exe" -c "import rstcheck;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'rstcheck'

Error: Command failed: "C:\Users\daniel\miniconda3\envs\docs\python.exe" -c "import rstcheck;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'rstcheck'

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

The plugin offers to install it via a VS Code dialog, but fails to install it:

```
[Log - 22:15:20] Started to install rstcheck...
[Log - 22:15:20] Running cmd: "C:\Users\daniel\miniconda3\envs\docs\python.exe" -m pip install rstcheck
[Log - 22:15:29] Error
Command failed: "C:\Users\daniel\miniconda3\envs\docs\python.exe" -m pip install rstcheck
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/rstcheck/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/rstcheck/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/rstcheck/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/rstcheck/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/rstcheck/
ERROR: Could not find a version that satisfies the requirement rstcheck (from versions: none)
ERROR: No matching distribution found for rstcheck
```

## Suggested solution

lexstudio's restructured should activate the environment first, instead of calling python in the env's folder. I can install rstcheck manually by doing so.

### Extension information

176.0.0

### Visual Studio Code information

1.65.1

### Operating system information

Windows 10

### Python information

3.9.5

### Sphinx information

4.4

**Comment by danieltuzes** [comment]
What is the resolution?

**Comment by lextm** [comment]
This extension does not handle dependency installation under every possible situation.

venv support is not going to be covered in individual reports like this.

**Comment by danieltuzes** [comment]
It is not a venv.

**Comment by lextm** [comment]
As long as you can manually install rstcheck, this extension won't take further steps itself. Resolving issues like "pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available" goes far from the scope.
