### ISSUE TITLE
A request has failed. See the output for more information

### ISSUE THREAD

**Issue by mlategan** [vscode-restructuredtext/vscode-restructuredtext#360]
I get the this message each time I save a .rst file:

![scr1](https://user-images.githubusercontent.com/21269704/158476528-96027963-8cc6-4f5c-8a01-12a736684c37.png)

The output give this:

```
The HTML pages are in source/_build/html.
Traceback (most recent call last):
  File "/opt/development/projects/bwm-docs/.venv/lib/python3.9/site-packages/pygls/protocol.py", line 152, in deserialize_message
    deserialize_params(data, get_params_type)
  File "/opt/development/projects/bwm-docs/.venv/lib/python3.9/site-packages/pygls/protocol.py", line 138, in deserialize_params
    data['params'] = params_type(**params)
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CodeActionParams
context -> only -> 0
  value is not a valid enumeration member; permitted: '', 'quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source', 'source.organizeImports' (type=type_error.enum; enum_values=[<CodeActionKind.Empty: ''>, <CodeActionKind.QuickFix: 'quickfix'>, <CodeActionKind.Refactor: 'refactor'>, <CodeActionKind.RefactorExtract: 'refactor.extract'>, <CodeActionKind.RefactorInline: 'refactor.inline'>, <CodeActionKind.RefactorRewrite: 'refactor.rewrite'>, <CodeActionKind.Source: 'source'>, <CodeActionKind.SourceOrganizeImports: 'source.organizeImports'>])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/development/projects/bwm-docs/.venv/lib/python3.9/site-packages/esbonio/__main__.py", line 8, in <module>
    sys.exit(main(cli))
  File "/opt/development/projects/bwm-docs/.venv/lib/python3.9/site-packages/esbonio/cli.py", line 79, in main
    server.start_io()
  File "/opt/development/projects/bwm-docs/.venv/lib/python3.9/site-packages/pygls/server.py", line 204, in start_io
    self.loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/development/projects/bwm-docs/.venv/lib/python3.9/site-packages/pygls/server.py", line 75, in aio_readline
    proxy(b''.join(message))
  File "/opt/development/projects/bwm-docs/.venv/lib/python3.9/site-packages/pygls/protocol.py", line 456, in data_received
    json.loads(body.decode(self.CHARSET),
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/opt/development/projects/bwm-docs/.venv/lib/python3.9/site-packages/pygls/protocol.py", line 154, in deserialize_message
    raise JsonRpcInvalidParams()
pygls.exceptions.JsonRpcInvalidParams: Invalid Params
[Info  - 23:22:02] Connection to server got closed. Server will restart.
[Error - 23:22:02] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Pipe.<anonymous> (net.js:673:12)
```

**Comment by lextm** [comment]
Sounds like your folder contains something pydantic doesn't like,  https://github.com/samuelcolvin/pydantic

Can you search and resolve that and try again?

**Comment by mlategan** [comment]
Thanks for the reply. I started with a clean folder and did the following:
```
python3 -m venv .venv
source .venv/bin/activate
pip install doc8 rstcheck
pip install sphinx sphinx-autobuild
sphinx-quickstart
```
I chose to have separate source and build folders.

The I opened vscode, navigated to the created source/index.rst without changing anything and then hit CTRL-S to save it. And that generated the error.

Any ideas what pydantic could be on about?

**Comment by alcarney** [comment]
So it appears like VSCode is making a [`textDocument/codeAction`](https://microsoft.github.io/language-server-protocol/specification.html#textDocument_codeAction) request to esbonio and pydantic is complaining about the parameters it has been given. - Why I have no idea...

Can you share your VSCode version and the output of `pip list`?

Also can you try it again after setting `"esbonio.trace.server": "verbose"` in VSCode and share the output log? Hopefully that will let use see exactly what VSCode is sending to the server.

**Comment by mlategan** [comment]
VSCode:

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-35-generic

pip list:
```
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
appdirs                       1.4.4
Babel                         2.9.1
certifi                       2021.10.8
charset-normalizer            2.0.12
colorama                      0.4.4
doc8                          0.10.1
docutils                      0.17.1
esbonio                       0.9.0
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.3
Jinja2                        3.0.3
livereload                    2.6.3
MarkupSafe                    2.1.1
packaging                     21.3
pbr                           5.8.1
pip                           20.3.4
pkg-resources                 0.0.0
pydantic                      1.8.2
pygls                         0.11.3
Pygments                      2.11.2
pyparsing                     3.0.7
pyspellchecker                0.6.3
pytz                          2021.3
requests                      2.27.1
restructuredtext-lint         1.4.0
rstcheck                      3.3.1
setuptools                    44.1.1
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        4.4.0
sphinx-autobuild              2021.3.14
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stevedore                     3.5.0
tornado                       6.1
typeguard                     2.13.3
typing-extensions             4.1.1
urllib3                       1.26.8
zipp                          3.7.0
```

Output Log:

```
[Trace - 01:17:45] Sending request 'textDocument/codeAction - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///opt/development/projects/test/source/index.rst"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 20,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [],
        "only": [
            "source.fixAll"
        ]
    }
}


Traceback (most recent call last):
  File "/opt/development/projects/test/.venv/lib/python3.9/site-packages/pygls/protocol.py", line 152, in deserialize_message
    deserialize_params(data, get_params_type)
  File "/opt/development/projects/test/.venv/lib/python3.9/site-packages/pygls/protocol.py", line 138, in deserialize_params
    data['params'] = params_type(**params)
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CodeActionParams
context -> only -> 0
  value is not a valid enumeration member; permitted: '', 'quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source', 'source.organizeImports' (type=type_error.enum; enum_values=[<CodeActionKind.Empty: ''>, <CodeActionKind.QuickFix: 'quickfix'>, <CodeActionKind.Refactor: 'refactor'>, <CodeActionKind.RefactorExtract: 'refactor.extract'>, <CodeActionKind.RefactorInline: 'refactor.inline'>, <CodeActionKind.RefactorRewrite: 'refactor.rewrite'>, <CodeActionKind.Source: 'source'>, <CodeActionKind.SourceOrganizeImports: 'source.organizeImports'>])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/development/projects/test/.venv/lib/python3.9/site-packages/esbonio/__main__.py", line 8, in <module>
    sys.exit(main(cli))
  File "/opt/development/projects/test/.venv/lib/python3.9/site-packages/esbonio/cli.py", line 79, in main
    server.start_io()
  File "/opt/development/projects/test/.venv/lib/python3.9/site-packages/pygls/server.py", line 204, in start_io
    self.loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/development/projects/test/.venv/lib/python3.9/site-packages/pygls/server.py", line 75, in aio_readline
    proxy(b''.join(message))
  File "/opt/development/projects/test/.venv/lib/python3.9/site-packages/pygls/protocol.py", line 456, in data_received
    json.loads(body.decode(self.CHARSET),
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/opt/development/projects/test/.venv/lib/python3.9/site-packages/pygls/protocol.py", line 154, in deserialize_message
    raise JsonRpcInvalidParams()
pygls.exceptions.JsonRpcInvalidParams: Invalid Params
[Info  - 01:17:45] Connection to server got closed. Server will restart.
[Error - 01:17:45] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at Object.dispose (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-languageclient/lib/client.js:2309:42)
    at LanguageClient.handleConnectionClosed (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-languageclient/lib/main.js:155:15)
    at closeHandler (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-languageclient/lib/client.js:2296:18)
    at CallbackList.invoke (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/home/morne/.vscode/extensions/lextudio.restructuredtext-178.0.0/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Pipe.<anonymous> (net.js:673:12)
[Trace - 01:17:45] Sending request 'initialize - (0)'.
Params: {
    "processId": 426699,
    "clientInfo": {
        "name": "vscode",
        "version": "1.65.2"
    },
    "rootPath": "/opt/development/projects/test",
    "rootUri": "file:///opt/development/projects/test",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                }
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    }
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            }
        },
        "window": {
            "workDoneProgress": true
        }
    },
    "initializationOptions": {
        "sphinx": {
            "srcDir": null,
            "confDir": "/opt/development/projects/test/source",
            "buildDir": "/opt/development/projects/test/source/_build"
        },
        "server": {
            "logLevel": "error",
            "logFilter": [],
            "hideSphinxOutput": false
        }
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///opt/development/projects/test",
            "name": "test"
        }
    ]
}


[Trace - 01:17:45] Received response 'initialize - (0)' in 336ms.
Result: {
    "capabilities": {
        "textDocumentSync": {
            "openClose": true,
            "change": 2,
            "willSave": false,
            "willSaveWaitUntil": false,
            "save": true
        },
        "completionProvider": {
            "triggerCharacters": [
                ".",
                ":",
                "`",
                "<",
                "/"
            ],
            "resolveProvider": true
        },
        "definitionProvider": true,
        "documentSymbolProvider": true,
        "codeActionProvider": true,
        "executeCommandProvider": {
            "commands": [
                "esbonio.server.configuration"
            ]
        },
        "workspace": {
            "workspaceFolders": {
                "supported": true,
                "changeNotifications": true
            },
            "fileOperations": {
                "didDelete": {
                    "filters": [
                        {
                            "pattern": {
                                "glob": "**/*.rst"
                            }
                        }
                    ]
                }
            }
        }
    }
}


[Trace - 01:17:45] Sending notification 'initialized'.
Params: {}


[Trace - 01:17:45] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///opt/development/projects/test/source/index.rst",
        "languageId": "restructuredtext",
        "version": 1,
        "text": ".. test documentation master file, created by\n   sphinx-quickstart on Wed Mar 16 00:19:53 2022.\n   You can adapt this file completely to your liking, but it should at least\n   contain the root `toctree` directive.\n\nWelcome to test's documentation!\n================================\n\n.. toctree::\n   :maxdepth: 2\n   :caption: Contents:\n\n\n\nIndices and tables\n==================\n\n* :ref:`genindex`\n* :ref:`modindex`\n* :ref:`search`\n"
    }
}


[Trace - 01:17:45] Sending request 'textDocument/documentSymbol - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///opt/development/projects/test/source/index.rst"
    }
}


[Trace - 01:17:45] Sending request 'textDocument/codeAction - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///opt/development/projects/test/source/index.rst"
    },
    "range": {
        "start": {
            "line": 10,
            "character": 22
        },
        "end": {
            "line": 10,
            "character": 22
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "building [mo]: targets for 0 po files that are out of date"
}


building [mo]: targets for 0 po files that are out of date
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "building [html]: targets for 1 source files that are out of date"
}


building [html]: targets for 1 source files that are out of date
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "updating environment:"
}


updating environment:
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[new config]"
}


[new config]
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "1 added, 0 changed, 0 removed"
}


1 added, 0 changed, 0 removed
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "reading sources... [100%] index"
}


reading sources... [100%] index
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": ""
}



[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "looking for now-outdated files..."
}


looking for now-outdated files...
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "none found"
}


none found
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "pickling environment..."
}


pickling environment...
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "done"
}


done
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "checking consistency..."
}


checking consistency...
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "done"
}


done
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "preparing documents..."
}


preparing documents...
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "done"
}


done
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "writing output... [100%] index"
}


writing output... [100%] index
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": ""
}



[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "generating indices..."
}


generating indices...
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "genindex"
}


genindex
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "done"
}


done
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "writing additional pages..."
}


writing additional pages...
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "search"
}


search
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "done"
}


done
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "copying static files..."
}


copying static files...
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "done"
}


done
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "copying extra files..."
}


copying extra files...
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "done"
}


done
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "dumping search index in English (code: en)..."
}


dumping search index in English (code: en)...
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "done"
}


done
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "dumping object inventory..."
}


dumping object inventory...
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "done"
}


done
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "build succeeded."
}


build succeeded.
[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": ""
}



[Trace - 01:17:45] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "The HTML pages are in source/_build/html."
}


The HTML pages are in source/_build/html.
[Trace - 01:17:45] Received response 'textDocument/documentSymbol - (1)' in 207ms.
Result: [
    {
        "name": "Welcome to test’s documentation!",
        "kind": 15,
        "range": {
            "start": {
                "line": 6,
                "character": 0
            },
            "end": {
                "line": 6,
                "character": 31
            }
        },
        "selectionRange": {
            "start": {
                "line": 6,
                "character": 0
            },
            "end": {
                "line": 6,
                "character": 31
            }
        },
        "children": []
    },
    {
        "name": "Indices and tables",
        "kind": 15,
        "range": {
            "start": {
                "line": 15,
                "character": 0
            },
            "end": {
                "line": 15,
                "character": 17
            }
        },
        "selectionRange": {
            "start": {
                "line": 15,
                "character": 0
            },
            "end": {
                "line": 15,
                "character": 17
            }
        },
        "children": []
    }
]


[Trace - 01:17:45] Received response 'textDocument/codeAction - (2)' in 206ms.
Result: []


[Trace - 01:17:50] Sending request 'textDocument/codeAction - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///opt/development/projects/test/source/index.rst"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 20,
            "character": 0
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 01:17:50] Received response 'textDocument/codeAction - (3)' in 2ms.
Result: []


```

**Comment by mlategan** [comment]
Fixed it. I had this in my settings:
```
  "editor.codeActionsOnSave": {
    "source.fixAll": true,
    "source.addMissingImports": true
  },
```

Removing both source entries fixed it.

**Comment by alcarney** [comment]
Glad to hear it! 

Looks like `source.fixAll` is a new code action kind that is being added in the upcoming version of the LSP spec... shame that the server implodes because of it....

**Comment by mlategan** [comment]
I picked it up here:

https://github.com/microsoft/vscode/issues/87227

It looks like it is an old action code that has been discontinued. So all my bad for using it, probably copied it from some old forum long ago.
