### ISSUE TITLE
[Bug]: Esbonio crashes on an import error

### ISSUE THREAD

**Issue by Neykah** [vscode-restructuredtext/vscode-restructuredtext#361]
### Expected behavior

When starting VSCode, I expected the Esbonio language server to start without problem.

### Actual behavior

But the following pop-up windows showed up:

> A request has failed. See the output for more information.

> The Esbonio Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

When checking the `Output (Esbonio)` logs, the following messages appear:

```
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/morganl/Library/Caches/pypoetry/virtualenvs/bh-sustech-H99fDYJb-py3.8/lib/python3.8/site-packages/esbonio/__main__.py", line 5, in <module>
    from esbonio.lsp.sphinx import cli
  File "/Users/morganl/Library/Caches/pypoetry/virtualenvs/bh-sustech-H99fDYJb-py3.8/lib/python3.8/site-packages/esbonio/lsp/sphinx/__init__.py", line 30, in <module>
    from sphinx.application import Sphinx
  File "/Users/morganl/Library/Caches/pypoetry/virtualenvs/bh-sustech-H99fDYJb-py3.8/lib/python3.8/site-packages/sphinx/application.py", line 31, in <module>
    from sphinx.config import Config
  File "/Users/morganl/Library/Caches/pypoetry/virtualenvs/bh-sustech-H99fDYJb-py3.8/lib/python3.8/site-packages/sphinx/config.py", line 24, in <module>
    from sphinx.util.tags import Tags
  File "/Users/morganl/Library/Caches/pypoetry/virtualenvs/bh-sustech-H99fDYJb-py3.8/lib/python3.8/site-packages/sphinx/util/tags.py", line 11, in <module>
    from jinja2 import nodes
  File "/Users/morganl/Library/Caches/pypoetry/virtualenvs/bh-sustech-H99fDYJb-py3.8/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/Users/morganl/Library/Caches/pypoetry/virtualenvs/bh-sustech-H99fDYJb-py3.8/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/Users/morganl/Library/Caches/pypoetry/virtualenvs/bh-sustech-H99fDYJb-py3.8/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/Users/morganl/Library/Caches/pypoetry/virtualenvs/bh-sustech-H99fDYJb-py3.8/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/Users/morganl/Library/Caches/pypoetry/virtualenvs/bh-sustech-H99fDYJb-py3.8/lib/python3.8/site-packages/markupsafe/__init__.py)
[Error - 5:37:32 PM] Connection to server got closed. Server will not be restarted.
```

### Detailed steps

The problem starts right after opening VSCode.

### Extension information

178.0.0

### Visual Studio Code information

1.65.2

### Operating system information

macOS Monterey 12.1

### Python information

3.8

### Sphinx information

4.4.0

### Contents of conf.py

```python
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "BH"
copyright = "2022, Ridge-i"
author = "Ridge-i"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["sphinxcontrib.plantuml"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "alabaster"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

plantuml_output_format = "svg_img"
```

**Comment by Neykah** [comment]
I think I found the reason for the issue.
My previous setup included a lot of poetry dependencies which constrained my jinja version to be `2.11.13`
The bug happened with this version constraint.

After cleaning up my dependency list, I was able to run `poetry update` and update my jinja to `3.0.3`.
Then, the above mentioned bug doesn't happen anymore.
Sorry for raising the issue too fast, I will close it.

**Comment by lextm** [comment]
Oh, please keep reporting such issues in the future.

Esbonio is still a very young project (over 1k active users a few weeks ago), while after integrating with this extension thousands of more active users are coming with various kinds of setup (including yours). So every reports can help improve it (especially on what should be improved on error handling).
