### ISSUE TITLE
[Bug]: Esbonio does not pick up everything from conf.py

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#367]
### Expected behavior

When I run Esbonio, I expect it to compile my project.

Also, when there is a failure in Esbonio, I expect to be able to find the exact details on how Sphinx was invoked: which Python, any enviornment variables, etc. so I can reproduce in a command shell and debug it.

### Actual behavior

Instead I get an error indicating that Esbonio didn't pick up a configuration change from conf.py:

```
[Error - 1:15:45 PM] Starting client failed
Error: command 'esbonio.server.configuration' already exists
	at _.registerCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:109536)
	at Object.registerCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:20898)
	at ExecuteCommandFeature.register (/home/oyvind/.vscode/extensions/lextudio.restructuredtext-180.0.0/node_modules/vscode-languageclient/lib/client.js:1650:53)
	at ExecuteCommandFeature.initialize (/home/oyvind/.vscode/extensions/lextudio.restructuredtext-180.0.0/node_modules/vscode-languageclient/lib/client.js:1630:14)
	at LanguageClient.initializeFeatures (/home/oyvind/.vscode/extensions/lextudio.restructuredtext-180.0.0/node_modules/vscode-languageclient/lib/client.js:2462:21)
	at /home/oyvind/.vscode/extensions/lextudio.restructuredtext-180.0.0/node_modules/vscode-languageclient/lib/client.js:2147:18
[esbonio.lsp] Workspace root file://[deleted]/docs/architecture
[esbonio.lsp] Sphinx Config {'version': None, 'conf_dir': '[deleted]/docs/architecture', 'src_dir': None, 'build_dir': '[deleted]/docs/architecture/_build', 'builder_name': 'html'}
[esbonio.lsp] Config dir [deleted]/docs/architecture
[esbonio.lsp] Src dir [deleted]/docs/architecture
[esbonio.lsp] Build dir [deleted]/docs/architecture/_build/html
[esbonio.lsp] Doctree dir [deleted]/docs/architecture/_build/doctrees
[esbonio.lsp] Building...

[esbonio.lsp] Traceback (most recent call last):
  File "[deleted].tox/py3/lib/python3.9/site-packages/esbonio/lsp/sphinx/__init__.py", line 343, in build
    self.app.build()
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 308, in build
    updated_docnames = set(self.read())
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 415, in read
    self._read_serial(docnames)
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 436, in _read_serial
    self.read_doc(docname)
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 476, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinx/io.py", line 189, in read_doc
    pub.publish()
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinx/io.py", line 109, in read
    self.parse()
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinx/parsers.py", line 101, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "[deleted].tox/py3/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinx/domains/__init__.py", line 286, in run
    return super().run()
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinxcontrib/datatemplates/directive.py", line 185, in run
    rendered_template = render_function(
  File "[deleted].tox/py3/lib/python3.9/site-packages/sphinx/jinja2glue.py", line 199, in render_string
    return self.environment.from_string(source).render(context)
  File "[deleted].tox/py3/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "[deleted].tox/py3/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "[deleted].tox/py3/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateAssertionError: No filter named 'union'.
```

### Detailed steps

Load project with some modifications to conf.py.

### Extension information

v180.0.0

### Visual Studio Code information

1.60.0

### Operating system information

Ubuntu 21

### Python information

3.9.7

### Sphinx information

4.4.0

### Contents of conf.py

```python
It's the "union" below that is not picked up so jinja2 fails.


from jinja2.filters import environmentfilter
from jinja2.filters import do_unique


@environmentfilter
def intersect(environment, a, b):
    return set(a) & set(b)


@environmentfilter
def union(environment, a, b):
    return set(a) | set(b)


@environmentfilter
def minus(environment, a, b):
    return set(a) - set(b)


@environmentfilter
def flatten(environment, a):
    return itertools.chain(*a)


@environmentfilter
def dump_yaml(environment, a):
    return yaml.dump(a)


def add_jinja_filters(app):
    app.builder.templates.environment.filters['intersect'] = intersect
    app.builder.templates.environment.filters['union'] = union
    app.builder.templates.environment.filters['minus'] = minus
    app.builder.templates.environment.filters['flatten'] = flatten
    app.builder.templates.environment.filters['dump_yaml'] = dump_yaml


def setup(app):
    app.connect("builder-inited", add_jinja_filters)
```
```


### Relevant log output

_No response_

**Comment by oharboe** [comment]
Aha!

The problem is that I'm extending jinja2 in conf.py, whereas I guess it really should be done in a Sphinx extension.

Once I move the above to a Sphinx extension, the strange error in Esbonio disappeared.

I wonder if it is useful for the developers of this plugin to be aware of this snag...

Please close this github issue after reading this message.

**Comment by alcarney** [comment]
Interesting.... I would expect that to work as I've [extended](https://github.com/swyddfa/esbonio/blob/4a6c9111a6e15a8f347730f6eb01fc4487133287/docs/conf.py#L129) Sphinx in Esbonio's `conf.py` and it seems to work fine.

Did your `conf.py` version of the jinja extension work when running Sphinx outside the editor?

>  I expect to be able to find the exact details on how Sphinx was invoked: which Python, any enviornment variables, etc. so I can reproduce in a command shell and debug it.

That would be a useful!

**Comment by oharboe** [comment]
> 



> Interesting.... I would expect that to work as I've [extended](https://github.com/swyddfa/esbonio/blob/4a6c9111a6e15a8f347730f6eb01fc4487133287/docs/conf.py#L129) Sphinx in Esbonio's `conf.py` and it seems to work fine.
> 
> Did your `conf.py` version of the jinja extension work when running Sphinx outside the editor?

Yes.
