### ISSUE TITLE
[Bug]: Unknown directive type "toctree"

### ISSUE THREAD

**Issue by Dragorn421** [vscode-restructuredtext/vscode-restructuredtext#386]
### Expected behavior

I expected the sphinx-specific directive `toctree` to be previewed in the restructuredtext preview.

The `restructuredtext.preview.name` setting is (correctly, I assume) set to sphinx (the default):

![image](https://user-images.githubusercontent.com/5306619/164782922-c02f5c10-6491-482e-a40a-88803cf29931.png)

### Actual behavior

But the preview shows an `Unknown directive type "toctree"` error instead:

```
System Message: ERROR/3 (/home/dragorn421/zelda64-dragodoc/index.rst, line 9)

Unknown directive type "toctree".

.. toctree::
   :maxdepth: 2
   :caption: Contents:
```

### Detailed steps

Clone https://github.com/Dragorn421/zelda64-dragodoc/tree/563c03fff29c581f9c285c68a7c828de56564564 (I don't know maybe there's something specific about my project)

Make sure `restructuredtext.preview.name` is set to `Sphinx`

Open preview for https://github.com/Dragorn421/zelda64-dragodoc/blob/563c03fff29c581f9c285c68a7c828de56564564/index.rst

See an error about `toctree`

### Extension information

186.0.0

### Visual Studio Code information

1.66.2

### Operating system information

Ubuntu 18.04 in WSL2 on Windows 10 21H1

### Python information

3.6.9

### Sphinx information

4.5.0

### Contents of conf.py

https://github.com/Dragorn421/zelda64-dragodoc/blob/563c03fff29c581f9c285c68a7c828de56564564/conf.py

### Relevant log output

Full log in extension output shortly after starting VS Code:

<details>

```
[Log - 9:33:59 PM] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 9:34:00 PM] OS is linux
[Log - 9:34:00 PM] dist: ubuntu
[Log - 9:34:00 PM] Running cmd: "/usr/bin/python3" -c "import sys; print(sys.version_info[0])"
[Log - 9:34:04 PM] Successful exec
[Log - 9:34:04 PM] Running cmd: "/usr/bin/python3" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.0'))"
[Log - 9:34:09 PM] Successful exec
[Log - 9:34:09 PM] Running cmd: "/usr/bin/python3" -c "import docutils;"
[Log - 9:34:09 PM] Successful exec
[Log - 9:34:09 PM] Running cmd: "/usr/bin/python3" -c "import doc8.main;"
[Log - 9:34:10 PM] Error
Command failed: "/usr/bin/python3" -c "import doc8.main;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'doc8'

Error: Command failed: "/usr/bin/python3" -c "import doc8.main;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'doc8'

	at ChildProcess.exithandler (node:child_process:397:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'doc8'

[Log - 9:34:10 PM] Running cmd: "/usr/bin/python3" -c "import rstcheck;"
[Log - 9:34:10 PM] Error
Command failed: "/usr/bin/python3" -c "import rstcheck;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'rstcheck'

Error: Command failed: "/usr/bin/python3" -c "import rstcheck;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'rstcheck'

	at ChildProcess.exithandler (node:child_process:397:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'rstcheck'

[Log - 9:34:10 PM] Running cmd: "/usr/bin/python3" -c "import restructuredtext_lint;"
[Log - 9:34:10 PM] Error
Command failed: "/usr/bin/python3" -c "import restructuredtext_lint;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'restructuredtext_lint'

Error: Command failed: "/usr/bin/python3" -c "import restructuredtext_lint;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'restructuredtext_lint'

	at ChildProcess.exithandler (node:child_process:397:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'restructuredtext_lint'

[Log - 9:34:10 PM] Running cmd: "/usr/bin/python3" -c "import platform; from distutils.version import LooseVersion; print(LooseVersion(platform.python_version()) < LooseVersion('3.6.0'))"
[Log - 9:34:10 PM] Successful exec
[Log - 9:34:10 PM] Running cmd: "/usr/bin/python3" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.0'))"
[Log - 9:34:11 PM] Successful exec
[Log - 9:34:15 PM] [preview] set config to 
[Log - 9:34:16 PM] [preview] Compiling file: /home/dragorn421/zelda64-dragodoc/index.rst
[Log - 9:34:16 PM] Running cmd: "/usr/bin/python3" "/home/dragorn421/.vscode-server/extensions/lextudio.restructuredtext-186.0.0/python-scripts/preview.py" "/home/dragorn421/zelda64-dragodoc/index.rst" "html" "html_body"
[Log - 9:34:16 PM] Successful exec
[Log - 9:34:23 PM] [preview] Compiling file: /home/dragorn421/zelda64-dragodoc/index.rst
[Log - 9:34:23 PM] Running cmd: "/usr/bin/python3" "/home/dragorn421/.vscode-server/extensions/lextudio.restructuredtext-186.0.0/python-scripts/preview.py" "/home/dragorn421/zelda64-dragodoc/index.rst" "html" "html_body"
[Log - 9:34:24 PM] Successful exec
```

</details>

New log in developer tools console output after refreshing the preview:

<details>

```
  ERR Cannot read properties of undefined (reading 'children'): TypeError: Cannot read properties of undefined (reading 'children')
	at RstSectionProvider.provideDocumentSymbols (/home/dragorn421/.vscode-server/extensions/trond-snekvik.simple-rst-1.5.2/out/extension.js:52:41)
	at _.provideDocumentSymbols (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:85:95543)
	at /home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:85:123957
	at Q._withAdapter (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:85:123102)
	at Q.$provideDocumentSymbols (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:85:123935)
	at i._doInvokeHandler (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:89:13826)
	at i._invokeHandler (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:89:13510)
	at i._receiveRequest (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:89:12119)
	at i._receiveOneMessage (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:89:10841)
	at /home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:89:8947
	at u.invoke (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at /home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:104:34275
	at u.invoke (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at o._receiveMessage (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:23615)
	at /home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:21149
	at u.invoke (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at v.acceptChunk (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:15865)
	at /home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:14995
	at u.invoke (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at l._processReadQueue (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:104:21305)
	at l.acceptFrame (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:104:20961)
	at E._acceptChunk (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:104:18925)
	at /home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:104:15914
	at Socket.T (/home/dragorn421/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:104:13797)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
resourceLoading.ts:82 Error: Unable to read file 'vscode-remote://wsl+ubuntu-18.04_d/vscode-resource?{"requestResourcePath":"/home/dragorn421/.vscode-server/extensions/lextudio.restructuredtext-186.0.0/media/basic.css"}' (Error: Unable to resolve nonexistent file 'vscode-remote://wsl+ubuntu-18.04_d/vscode-resource?{"requestResourcePath":"/home/dragorn421/.vscode-server/extensions/lextudio.restructuredtext-186.0.0/media/basic.css"}')
    at p.doReadFileStream (fileService.ts:573:11)
    at async w (resourceLoading.ts:68:18)
    at async n.loadResource (webviewElement.ts:719:19)
resourceLoading.ts:82 Error: Unable to read file 'vscode-remote://wsl+ubuntu-18.04_d/vscode-resource?{"requestResourcePath":"/home/dragorn421/.vscode-server/extensions/lextudio.restructuredtext-186.0.0/media/default.css"}' (Error: Unable to resolve nonexistent file 'vscode-remote://wsl+ubuntu-18.04_d/vscode-resource?{"requestResourcePath":"/home/dragorn421/.vscode-server/extensions/lextudio.restructuredtext-186.0.0/media/default.css"}')
    at p.doReadFileStream (fileService.ts:573:11)
    at async w (resourceLoading.ts:68:18)
    at async n.loadResource (webviewElement.ts:719:19)
resourceLoading.ts:82 Error: Unable to read file 'vscode-remote://wsl+ubuntu-18.04_d/vscode-resource?{"requestResourcePath":"/home/dragorn421/.vscode-server/extensions/lextudio.restructuredtext-186.0.0/media/rst.css"}' (Error: Unable to resolve nonexistent file 'vscode-remote://wsl+ubuntu-18.04_d/vscode-resource?{"requestResourcePath":"/home/dragorn421/.vscode-server/extensions/lextudio.restructuredtext-186.0.0/media/rst.css"}')
    at p.doReadFileStream (fileService.ts:573:11)
    at async w (resourceLoading.ts:68:18)
    at async n.loadResource (webviewElement.ts:719:19)
main.js:910          GET https://vscode-remote+wsl-002bubuntu-002d18-002e04-005fd.vscode-resource.vscode-webview.net/home/dragorn421/.vscode-server/extensions/lextudio.restructuredtext-186.0.0/media/basic.css net::ERR_ABORTED 404
(anonymous) @ main.js:910
setTimeout (async)
y @ main.js:908
(anonymous) @ main.js:939
main.js:910          GET https://vscode-remote+wsl-002bubuntu-002d18-002e04-005fd.vscode-resource.vscode-webview.net/home/dragorn421/.vscode-server/extensions/lextudio.restructuredtext-186.0.0/media/default.css net::ERR_ABORTED 404
(anonymous) @ main.js:910
setTimeout (async)
y @ main.js:908
(anonymous) @ main.js:939
main.js:910          GET https://vscode-remote+wsl-002bubuntu-002d18-002e04-005fd.vscode-resource.vscode-webview.net/home/dragorn421/.vscode-server/extensions/lextudio.restructuredtext-186.0.0/media/rst.css net::ERR_ABORTED 404
```

</details>

### Related issues?

https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/288 Unkown directive type "toctree"

https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/321 cannot preview rst files

**Comment by lextm** [comment]
That setting `restructuredtext.preview.name` alone won't give you sphinx based preview. You must also set `esbonio.sphinx.confDir` to a valid path, instead of `""`.

**Comment by yanquer** [comment]
my config:
"restructuredtext.preview.name": "sphinx",
"esbonio.sphinx.confDir": "${workspaceFolder}/source",

=====
but, nothing use.

<img width="440" alt="image" src="https://user-images.githubusercontent.com/95375182/206336721-b4bada4f-5547-4dd3-80d0-f56ca4f94d2a.png">

**Comment by lextm** [comment]
@yanquer Please read the original issue carefully. What you hit is that `rst-lint` does not understand `toctree` which is by design.
