### ISSUE TITLE
[Bug]: Saving Python files cause the Esbonio tab to steal focus

### ISSUE THREAD

**Issue by MinchinWeb** [vscode-restructuredtext/vscode-restructuredtext#389]
### Expected behavior

I should be able to keep working in my Python files, and save them as I go, and my cursor shouldn't have its focus stolen to somewhere else. Also, the bottom tabs, if hidden, should stay hidden.

### Actual behavior

When I'm working on my the Python files of my project, randomly the *Esbonio Language Server* tab will suddenly appear, and then steal my cursor. I think this is a result of saving my Python files.

### Detailed steps

1) make changes in Python files
2) save file (Ctrl + S)
3) keep typing away on Python file
4) Wonder why what you're typing isn't showing up on the Python file anymore. Wonder why the *Esbonio Language Server* tab has suddenly appeared.

### Extension information

187.0.0

### Visual Studio Code information

1.67.1

### Operating system information

Windows 10

### Python information

3.10.4

### Sphinx information

4.5.0

### Contents of conf.py

```python
from datetime import datetime
import os
import re
import sys

import alabaster

sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../.."))
from battlestation import __version__

try:
    import django
except ImportError:
    pass
else:
    os.environ["DJANGO_SETTINGS_MODULE"] = "battlestation.settings"
    django.setup()


# -- General configuration ------------------------------------------------

needs_sphinx = "1.3"

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",  # requires Sphinx >=1.3
    "releases",
    "alabaster",
    "sphinx_click.ext",
]

releases_github_path = "minchinweb/repo"
# releases_debug = True

templates_path = ["_templates", alabaster.get_path()]
source_suffix = ".rst"
master_doc = "index"

# General information about the project.
project = "Burst Energy Payroll"
year = datetime.now().year
year = str(year)[-2:]
copyright = "2015-{}, me".format(year)
author = "me"

release = str(__version__)
p = re.compile("\d+\.\d+")
versionmatch = p.match(release)
version = versionmatch.group()

language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
pygments_style = "sphinx"
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

html_theme = "alabaster"
# html_theme_options = {}
# html_theme_path = []
# html_title = None
# html_short_title = None
html_logo = "favicon.png"
html_favicon = "favicon.png"
html_static_path = ["_static"]
# html_extra_path = []
html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
    "**": [
        "about.html",  # Alabaster - logo, github button + blurb
        "localtoc.html",  # Sphinx built-in
        "relations.html",  # Alabaster - standard
        "navigation.html",
        "searchbox.html",  # Sphinx built-in
        "sourcelink.html",  # Sphinx built-in -- link to the source of document, if enabled in html_show_sourcelink
    ]
}

# html_show_sourcelink = True
# html_show_sphinx = True
# html_show_copyright = True
# html_file_suffix = None
htmlhelp_basename = "BattleStationdoc"
```

### Relevant log output

```shell
D:\Code\repo\battlestation\core\views\ama.py:docstring of battlestation.core.views.ama.MonthlyMembershipView:27: WARNING: Definition list ends without a blank line; unexpected unindent.
reading sources... [ 50%] battlestation.core.views.clean
reading sources... [ 53%] battlestation.django_excel
D:\Code\repo\battlestation\docs\battlestation.django_excel.rst:7: WARNING: toctree contains reference to nonexisting document 'battlestation.django_excel.migrations'
reading sources... [ 57%] battlestation.mailer
D:\Code\repo\battlestation\docs\battlestation.mailer.rst:7: WARNING: toctree contains reference to nonexisting document 'battlestation.mailer.migrations'
D:\Code\repo\battlestation\mailer\resources.py:docstring of battlestation.mailer.resources.EmailCustomerListResource.skip_row:17: ERROR: Unexpected indentation.
reading sources... [ 60%] battlestation.quotes
D:\Code\repo\battlestation\docs\battlestation.quotes.rst:7: WARNING: toctree contains reference to nonexisting document 'battlestation.quotes.migrations'
reading sources... [ 64%] battlestation.quotes.utils
reading sources... [ 67%] battlestation.www
D:\Code\repo\battlestation\docs\battlestation.www.rst:7: WARNING: toctree contains reference to nonexisting document 'battlestation.www.migrations'
reading sources... [ 71%] changelog
D:\Code\repo\.venv\lib\site-packages\releases\__init__.py:374: FutureWarning: 
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  raise ValueError(msg.format(buried[0], str(buried[0].parent)))
D:\Code\repo\battlestation\urls.py:docstring of battlestation.urls:5: WARNING: Definition list ends without a blank line; unexpected unindent.
D:\Code\repo\battlestation\urls.py:docstring of battlestation.urls:7: ERROR: Unexpected indentation.
D:\Code\repo\battlestation\urls.py:docstring of battlestation.urls:9: WARNING: Block quote ends without a blank line; unexpected unindent.
D:\Code\repo\battlestation\docs\battlestation.core.rst:7: WARNING: toctree contains reference to nonexisting document 'battlestation.core.migrations'
D:\Code\repo\battlestation\core\resources.py:docstring of battlestation.core.resources.ConstructedCustomerResource.skip_row:17: ERROR: Unexpected indentation.
D:\Code\repo\battlestation\core\resources.py:docstring of battlestation.core.resources.SourceChequeResource.skip_row:17: ERROR: Unexpected indentation.
D:\Code\repo\battlestation\core\resources.py:docstring of battlestation.core.resources.SourceSignupResource.skip_row:17: ERROR: Unexpected indentation.
D:\Code\repo\battlestation\core\templatetags\battlestation_tags.py:docstring of battlestation.core.templatetags.battlestation_tags.make_range:10: ERROR: Unexpected indentation.
D:\Code\repo\battlestation\core\utils\enum.py:docstring of battlestation.core.utils.enum.CommissionStructures:12: ERROR: Unexpected indentation.
D:\Code\repo\battlestation\core\utils\enum.py:docstring of battlestation.core.utils.enum.CommissionStructures:41: ERROR: Unexpected indentation.
D:\Code\repo\battlestation\core\utils\__init__.py:docstring of battlestation.core.utils.between_ignore_none:1: ERROR: Unknown target name: "lower".
D:\Code\repo\battlestation\core\utils\__init__.py:docstring of battlestation.core.utils.between_ignore_none:3: ERROR: Unknown target name: "lower".
D:\Code\repo\battlestation\core\views\ama.py:docstring of battlestation.core.views.ama.MonthlyMembershipView:8: WARNING: Definition list ends without a blank line; unexpected unindent.
D:\Code\repo\battlestation\core\views\ama.py:docstring of battlestation.core.views.ama.MonthlyMembershipView:10: ERROR: Unexpected indentation.
D:\Code\repo\battlestation\core\views\ama.py:docstring of battlestation.core.views.ama.MonthlyMembershipView:12: WARNING: Block quote ends without a blank line; unexpected unindent.
D:\Code\repo\battlestation\core\views\ama.py:docstring of battlestation.core.views.ama.MonthlyMembershipView:14: ERROR: Unexpected indentation.
D:\Code\repo\battlestation\core\views\ama.py:docstring of battlestation.core.views.ama.MonthlyMembershipView:16: WARNING: Block quote ends without a blank line; unexpected unindent.
D:\Code\repo\battlestation\core\views\ama.py:docstring of battlestation.core.views.ama.MonthlyMembershipView:18: ERROR: Unexpected indentation.
D:\Code\repo\battlestation\core\views\ama.py:docstring of battlestation.core.views.ama.MonthlyMembershipView:20: WARNING: Block quote ends without a blank line; unexpected unindent.
D:\Code\repo\battlestation\core\views\ama.py:docstring of battlestation.core.views.ama.MonthlyMembershipView:25: WARNING: Definition list ends without a blank line; unexpected unindent.
Unexpected section title.

},
...
D:\Code\repo\battlestation\core\views\ama.py:docstring of battlestation.core.views.ama.MonthlyMembershipView:27: WARNING: Definition list ends without a blank line; unexpected unindent.
D:\Code\repo\battlestation\docs\battlestation.django_excel.rst:7: WARNING: toctree contains reference to nonexisting document 'battlestation.django_excel.migrations'
D:\Code\repo\battlestation\docs\battlestation.mailer.rst:7: WARNING: toctree contains reference to nonexisting document 'battlestation.mailer.migrations'
D:\Code\repo\battlestation\mailer\resources.py:docstring of battlestation.mailer.resources.EmailCustomerListResource.skip_row:17: ERROR: Unexpected indentation.
D:\Code\repo\battlestation\docs\battlestation.quotes.rst:7: WARNING: toctree contains reference to nonexisting document 'battlestation.quotes.migrations'
D:\Code\repo\battlestation\docs\battlestation.www.rst:7: WARNING: toctree contains reference to nonexisting document 'battlestation.www.migrations'
[esbonio.lsp] Traceback (most recent call last):
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "D:\Code\repo\.venv\lib\site-packages\releases\__init__.py", line 612, in generate_changelog
    doctree.walk(changelog_visitor)
  File "D:\Code\repo\.venv\lib\site-packages\docutils\nodes.py", line 191, in walk
    if child.walk(visitor):
  File "D:\Code\repo\.venv\lib\site-packages\docutils\nodes.py", line 191, in walk
    if child.walk(visitor):
  File "D:\Code\repo\.venv\lib\site-packages\docutils\nodes.py", line 183, in walk
    visitor.dispatch_visit(self)
  File "D:\Code\repo\.venv\lib\site-packages\docutils\nodes.py", line 2021, in dispatch_visit
    return method(node)
  File "D:\Code\repo\.venv\lib\site-packages\releases\__init__.py", line 595, in visit_bullet_list
    releases, _ = construct_releases(node.children, self.app)
  File "D:\Code\repo\.venv\lib\site-packages\releases\__init__.py", line 521, in construct_releases
    construct_entry_without_release(focus, issues, manager, log, rest)
  File "D:\Code\repo\.venv\lib\site-packages\releases\__init__.py", line 374, in construct_entry_without_release
    raise ValueError(msg.format(buried[0], str(buried[0].parent)))
ValueError: 
Found issue node (<bug #None>) buried inside another node:

<term><Issue backported="False" major="False" nodelist="[<raw: <#text: '[<span style=" ...'>>, <inline: <#text: ':'>>, <inline: <#text: ' '>>]" number="None" spec="None" type_="bug"/> SourceCheques: make it so only new cheques show as “changed” on</term>

Please double-check your ReST syntax! There is probably text in the above
output that will show you which part of your changelog to look at.

For example, indentation problems can accidentally generate nested definition
lists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Code\repo\.venv\lib\site-packages\esbonio\lsp\sphinx\__init__.py", line 557, in build
    self.app.build()
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\application.py", line 330, in build
    self.builder.build_update()
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\builders\__init__.py", line 286, in build_update
    self.build(to_build,
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\builders\__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\builders\__init__.py", line 407, in read
    self._read_serial(docnames)
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\builders\__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\builders\__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\io.py", line 181, in read_doc
    pub.publish()
  File "D:\Code\repo\.venv\lib\site-packages\docutils\core.py", line 219, in publish
    self.apply_transforms()
  File "D:\Code\repo\.venv\lib\site-packages\docutils\core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\transforms\__init__.py", line 79, in apply_transforms
    super().apply_transforms()
  File "D:\Code\repo\.venv\lib\site-packages\docutils\transforms\__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\transforms\__init__.py", line 380, in apply
    self.app.emit('doctree-read', self.document)
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\application.py", line 440, in emit
    return self.events.emit(event, *args, allowed_exceptions=allowed_exceptions)
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\events.py", line 102, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function generate_changelog at 0x000002CF7F2B00D0> for event 'doctree-read' threw an exception (exception: 
Found issue node (<bug #None>) buried inside another node:

<term><Issue backported="False" major="False" nodelist="[<raw: <#text: '[<span style=" ...'>>, <inline: <#text: ':'>>, <inline: <#text: ' '>>]" number="None" spec="None" type_="bug"/> SourceCheques: make it so only new cheques show as “changed” on</term>

Please double-check your ReST syntax! There is probably text in the above
output that will show you which part of your changelog to look at.

For example, indentation problems can accidentally generate nested definition
lists.
)
Traceback (most recent call last):
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "D:\Code\repo\.venv\lib\site-packages\releases\__init__.py", line 612, in generate_changelog
    doctree.walk(changelog_visitor)
  File "D:\Code\repo\.venv\lib\site-packages\docutils\nodes.py", line 191, in walk
    if child.walk(visitor):
  File "D:\Code\repo\.venv\lib\site-packages\docutils\nodes.py", line 191, in walk
    if child.walk(visitor):
  File "D:\Code\repo\.venv\lib\site-packages\docutils\nodes.py", line 183, in walk
    visitor.dispatch_visit(self)
  File "D:\Code\repo\.venv\lib\site-packages\docutils\nodes.py", line 2021, in dispatch_visit
    return method(node)
  File "D:\Code\repo\.venv\lib\site-packages\releases\__init__.py", line 595, in visit_bullet_list
    releases, _ = construct_releases(node.children, self.app)
  File "D:\Code\repo\.venv\lib\site-packages\releases\__init__.py", line 521, in construct_releases
    construct_entry_without_release(focus, issues, manager, log, rest)
  File "D:\Code\repo\.venv\lib\site-packages\releases\__init__.py", line 374, in construct_entry_without_release
    raise ValueError(msg.format(buried[0], str(buried[0].parent)))
ValueError: 
Found issue node (<bug #None>) buried inside another node:

<term><Issue backported="False" major="False" nodelist="[<raw: <#text: '[<span style=" ...'>>, <inline: <#text: ':'>>, <inline: <#text: ' '>>]" number="None" spec="None" type_="bug"/> SourceCheques: make it so only new cheques show as �changed� on</term>

Please double-check your ReST syntax! There is probably text in the above
output that will show you which part of your changelog to look at.

For example, indentation problems can accidentally generate nested definition
lists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Code\repo\.venv\lib\site-packages\esbonio\lsp\sphinx\__init__.py", line 557, in build
    self.app.build()
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\application.py", line 330, in build
    self.builder.build_update()
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\builders\__init__.py", line 286, in build_update
    self.build(to_build,
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\builders\__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\builders\__init__.py", line 407, in read
    self._read_serial(docnames)
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\builders\__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\builders\__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\io.py", line 181, in read_doc
    pub.publish()
  File "D:\Code\repo\.venv\lib\site-packages\docutils\core.py", line 219, in publish
    self.apply_transforms()
  File "D:\Code\repo\.venv\lib\site-packages\docutils\core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\transforms\__init__.py", line 79, in apply_transforms
    super().apply_transforms()
  File "D:\Code\repo\.venv\lib\site-packages\docutils\transforms\__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\transforms\__init__.py", line 380, in apply
    self.app.emit('doctree-read', self.document)
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\application.py", line 440, in emit
    return self.events.emit(event, *args, allowed_exceptions=allowed_exceptions)
  File "D:\Code\repo\.venv\lib\site-packages\sphinx\events.py", line 102, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function generate_changelog at 0x000002CF7F2B00D0> for event 'doctree-read' threw an exception (exception: 
Found issue node (<bug #None>) buried inside another node:

<term><Issue backported="False" major="False" nodelist="[<raw: <#text: '[<span style=" ...'>>, <inline: <#text: ':'>>, <inline: <#text: ' '>>]" number="None" spec="None" type_="bug"/> SourceCheques: make it so only new cheques show as �changed� on</term>

Please double-check your ReST syntax! There is probably text in the above
output that will show you which part of your changelog to look at.

For example, indentation problems can accidentally generate nested definition
lists.
)

[Log - 10:43:37 a.m.] Build complete {"config":{"sphinx":{"version":"4.5.0","confDir":"D:\\Code\\repo\\battlestation\\docs","srcDir":"D:\\Code\\repo\\battlestation\\docs","buildDir":"d:\\_build\\dirhtml\\html","builderName":"html"},"server":{"log_level":"error","log_filter":[],"hide_sphinx_output":false}},"error":true,"warnings":27}
Cancel notification for unknown message id "778"
```

**Comment by lextm** [comment]
Duplicate to #375
