### ISSUE TITLE
[Bug]: esbonio installation in conda environment not recognized

### ISSUE THREAD

**Issue by michaelweinold** [vscode-restructuredtext/vscode-restructuredtext#396]
### Expected behavior

vscode-restructuredtext recognizes the esbonio installation in a conda environment.

### Actual behavior

vscode-restructuredtext does not recognize the esbonio installation in a conda environment, instead prompting to install esbonio via pip:

<img width="471" alt="Screenshot 2022-07-19 at 21 26 23" src="https://user-images.githubusercontent.com/23102087/179835032-4cfb347a-7ce9-405a-b1f4-65564dc32cb8.png">

### Detailed steps

1. download miniconda
2. create conda environment
3. install prerequisites [as per documentation](https://docs.restructuredtext.net/articles/prerequisites.html)
4. try to show preview for a `rst` file

### Extension information

v189.0.0

### Visual Studio Code information

1.69.2

### Operating system information

macOS Monterey (M1 Pro) 12.4 (21F79)

### Python information

3.8

### Sphinx information

???

### Relevant log output

```shell
[Log - 9:26:15 PM] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 9:26:15 PM] OS is darwin
[Log - 9:26:15 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -c "import sys; print(sys.version_info[0])"
[Log - 9:26:15 PM] Successful exec
[Log - 9:26:15 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
[Log - 9:26:15 PM] Error
Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'esbonio'

Error: Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'esbonio'

	at ChildProcess.exithandler (node:child_process:406:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'esbonio'

[Log - 9:26:15 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -c "import docutils;"
[Log - 9:26:15 PM] Successful exec
[Log - 9:26:15 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -c "import doc8.main;"
[Log - 9:26:15 PM] Error
Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import doc8.main;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/doc8/__init__.py", line 1, in <module>
    from .main import doc8  # noqa
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/doc8/main.py", line 47, in <module>
    from doc8 import checks
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/doc8/checks.py", line 19, in <module>
    from docutils import nodes as docutils_nodes
ImportError: cannot import name 'nodes' from 'docutils' (unknown location)

Error: Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import doc8.main;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/doc8/__init__.py", line 1, in <module>
    from .main import doc8  # noqa
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/doc8/main.py", line 47, in <module>
    from doc8 import checks
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/doc8/checks.py", line 19, in <module>
    from docutils import nodes as docutils_nodes
ImportError: cannot import name 'nodes' from 'docutils' (unknown location)

	at ChildProcess.exithandler (node:child_process:406:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/doc8/__init__.py", line 1, in <module>
    from .main import doc8  # noqa
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/doc8/main.py", line 47, in <module>
    from doc8 import checks
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/doc8/checks.py", line 19, in <module>
    from docutils import nodes as docutils_nodes
ImportError: cannot import name 'nodes' from 'docutils' (unknown location)

[Log - 9:26:15 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -c "import rstcheck;"
[Log - 9:26:15 PM] Error
Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import rstcheck;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/rstcheck/__init__.py", line 45, in <module>
    import docutils.core
ModuleNotFoundError: No module named 'docutils.core'

Error: Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import rstcheck;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/rstcheck/__init__.py", line 45, in <module>
    import docutils.core
ModuleNotFoundError: No module named 'docutils.core'

	at ChildProcess.exithandler (node:child_process:406:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/rstcheck/__init__.py", line 45, in <module>
    import docutils.core
ModuleNotFoundError: No module named 'docutils.core'

[Log - 9:26:15 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -c "import restructuredtext_lint;"
[Log - 9:26:15 PM] Error
Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import restructuredtext_lint;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/restructuredtext_lint/__init__.py", line 3, in <module>
    from restructuredtext_lint.lint import lint, lint_file
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/restructuredtext_lint/lint.py", line 4, in <module>
    from docutils import utils
ImportError: cannot import name 'utils' from 'docutils' (unknown location)

Error: Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import restructuredtext_lint;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/restructuredtext_lint/__init__.py", line 3, in <module>
    from restructuredtext_lint.lint import lint, lint_file
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/restructuredtext_lint/lint.py", line 4, in <module>
    from docutils import utils
ImportError: cannot import name 'utils' from 'docutils' (unknown location)

	at ChildProcess.exithandler (node:child_process:406:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/restructuredtext_lint/__init__.py", line 3, in <module>
    from restructuredtext_lint.lint import lint, lint_file
  File "/opt/miniconda3/envs/menv/lib/python3.10/site-packages/restructuredtext_lint/lint.py", line 4, in <module>
    from docutils import utils
ImportError: cannot import name 'utils' from 'docutils' (unknown location)

[Log - 9:26:15 PM] [preview] set config to 
[Log - 9:26:15 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
[Log - 9:26:15 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -c "import platform; from distutils.version import LooseVersion; print(LooseVersion(platform.python_version()) < LooseVersion('3.6.0'))"
[Log - 9:26:15 PM] Error
Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'esbonio'

Error: Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'esbonio'

	at ChildProcess.exithandler (node:child_process:406:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'esbonio'

[Log - 9:26:15 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -c "import docutils;"
[Log - 9:26:15 PM] Successful exec
[Log - 9:26:15 PM] Successful exec
[Log - 9:26:15 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
[Log - 9:26:15 PM] Error
Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'esbonio'

Error: Command failed: "/opt/miniconda3/envs/menv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'esbonio'

	at ChildProcess.exithandler (node:child_process:406:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'esbonio'

[Log - 9:26:15 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -c "import pip; from distutils.version import LooseVersion; print(LooseVersion(pip.__version__) < LooseVersion('20.0.2'))"
[Log - 9:26:15 PM] Successful exec
[Log - 9:26:25 PM] Started to install Esbonio...
[Log - 9:26:25 PM] Running cmd: "/opt/miniconda3/envs/menv/bin/python" -m pip install esbonio --upgrade
[Log - 9:26:27 PM] Successful exec
[Log - 9:26:27 PM] Finished installing esbonio
```

**Comment by marcelo-lara** [comment]
+1
same issue here

**Comment by rowangayleschaefer** [comment]
+1
same issue here

**Comment by lextm** [comment]
Currently no plan to support conda or any other virtual environment option that requires the extra `activate` step. Pipenv is preferred and partially supported right now. #407

**Comment by lextm** [comment]
You have to refer to #410 to learn the right commands to acquire dependencies, not the original documentation.
