### ISSUE TITLE
Cannot see preview on visual studio code "command command 'restructuredtext.showPreviewToSide' not found"

### ISSUE THREAD

**Issue by schoudhary13** [vscode-restructuredtext/vscode-restructuredtext#424]
### Expected behavior

I expected it show the preview of the restructured text as a rendered output

### Actual behavior

But a bug happened like this,command 'restructuredtext.showPreviewToSide' not found

### Detailed steps

The steps are,

I created a new rst file, and wanted to see the preview, but could not. I have enabled "Extension Pack for reStructuredText v1.0.1" but still cannot see the preview.
i get this error ",command 'restructuredtext.showPreviewToSide' not found"

this is the output log

[Log - 2:55:24 PM] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 2:55:24 PM] OS is win32
[Log - 2:55:25 PM] Running cmd: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import sys; print(sys.version_info[0])"
[Log - 2:55:25 PM] Successful exec
[Log - 2:55:25 PM] Running cmd: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
[Log - 2:55:26 PM] Successful exec
[Log - 2:55:26 PM] Running cmd: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import docutils;"
[Log - 2:55:27 PM] Successful exec
[Log - 2:55:27 PM] Running cmd: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import doc8.main;"
[Log - 2:55:27 PM] Error
Command failed: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import doc8.main;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'doc8'

Error: Command failed: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import doc8.main;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'doc8'

	at ChildProcess.exithandler (node:child_process:408:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'doc8'

[Log - 2:55:27 PM] Running cmd: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import rstcheck;"
[Log - 2:55:27 PM] Error
Command failed: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import rstcheck;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'rstcheck'

Error: Command failed: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import rstcheck;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'rstcheck'

	at ChildProcess.exithandler (node:child_process:408:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'rstcheck'

[Log - 2:55:27 PM] Running cmd: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import restructuredtext_lint;"
[Log - 2:55:27 PM] Error
Command failed: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import restructuredtext_lint;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'restructuredtext_lint'

Error: Command failed: "C:\Users\shrddha\AppData\Local\Programs\Python\Python311\python.exe" -c "import restructuredtext_lint;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'restructuredtext_lint'

	at ChildProcess.exithandler (node:child_process:408:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'restructuredtext_lint'

### Extension information

Extension Pack for reStructuredText v1.0.1

### Visual Studio Code information

1.77.1

### Operating system information

Windows

### Python information

3.11

### Sphinx information

0,0

**Comment by lextm** [comment]
During initialization this extension usually shows notification via VS Code API and some of the notifications must be acknowledged by you.

If you don't dismiss all such notifications, the extension cannot fully register itself to VS Code and that's the cause of the error.
