### ISSUE TITLE
[Bug]: flake8 conflict causes esbonio lsp failure

### ISSUE THREAD

**Issue by avoidik** [vscode-restructuredtext/vscode-restructuredtext#433]
### Expected behavior

I would like this extension to work as intended together with flake8 if installed.

### Actual behavior

I am getting unexpected error in LSP server every time I hover over the linter highlights.

### Detailed steps

I have prepared a bare minimal repo to be able to reproduce described behavior:

1. Clone the repo `git clone https://github.com/avoidik/rst-bug-repro`
1. Step inside and run `cd rst-bug-repro ; ./init-venv.sh`
1. Activate python virtual environment `source .venv-sphinx/bin/activate`
1. Open project in vscode `code .`
1. Open `index.rst` file and hover over the long line no. 4

### Extension information

189.3.0

### Visual Studio Code information

1.83.1

### Operating system information

macOS arm64

### Python information

3.11.6

### Sphinx information

7.2.6

### Contents of conf.py

```python
"""Dummy file."""
```

### Relevant log output

```shell
[Trace - 13:23:15] Sending request 'textDocument/hover - (48)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/user.name/Projects/rst-bug-repro/project/index.rst"
    },
    "position": {
        "line": 3,
        "character": 35
    }
}


[Trace - 13:23:15] Received response 'textDocument/hover - (48)' in 2ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": ""
    }
}


[Trace - 13:23:15] Sending request 'textDocument/codeAction - (49)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/user.name/Projects/rst-bug-repro/project/index.rst"
    },
    "range": {
        "start": {
            "line": 3,
            "character": 0
        },
        "end": {
            "line": 3,
            "character": 1.7976931348623157e+308
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 3,
                        "character": 0
                    },
                    "end": {
                        "line": 3,
                        "character": 1.7976931348623157e+308
                    }
                },
                "message": "Line too long",
                "severity": 2,
                "code": "D001",
                "source": "doc8"
            }
        ],
        "only": [
            "quickfix"
        ]
    }
}


Unable to deserialize message
  + Exception Group Traceback (most recent call last):
  |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/pygls/protocol/json_rpc.py", line 329, in _deserialize_message
  |     return self._converter.structure(data, request_type)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/cattrs/converters.py", line 334, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>", line 26, in structure_TextDocumentCodeActionRequest
  |     if errors: raise __c_cve('While structuring ' + 'TextDocumentCodeActionRequest', errors, __cl)
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | cattrs.errors.ClassValidationError: While structuring TextDocumentCodeActionRequest (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>", line 10, in structure_TextDocumentCodeActionRequest
    |     res['params'] = __c_structure_params(o['params'], __c_type_params)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 31, in structure_CodeActionParams
    |     if errors: raise __c_cve('While structuring ' + 'CodeActionParams', errors, __cl)
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | cattrs.errors.ClassValidationError: While structuring CodeActionParams (2 sub-exceptions)
    | Structuring class TextDocumentCodeActionRequest @ attribute params
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 10, in structure_CodeActionParams
      |     res['range'] = __c_structure_range(o['range'], __c_type_range)
      |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "<cattrs generated structure lsprotocol.types.Range>", line 14, in structure_Range
      |     if errors: raise __c_cve('While structuring ' + 'Range', errors, __cl)
      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      | cattrs.errors.ClassValidationError: While structuring Range (1 sub-exception)
      | Structuring class CodeActionParams @ attribute range
      +-+---------------- 1 ----------------
        | Traceback (most recent call last):
        |   File "<cattrs generated structure lsprotocol.types.Position>", line 16, in structure_Position
        |     return __cl(
        |             ^^^^
        |   File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
        |     __attr_validator_character(self, __attr_character, self.character)
        |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/lsprotocol/validators.py", line 44, in uinteger_validator
        |     raise ValueError(
        | ValueError: Position.character should be in range [0:2147483647], but was 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.
        | 
        | During handling of the above exception, another exception occurred:
        | 
        | Exception Group Traceback (most recent call last):
        |   File "<cattrs generated structure lsprotocol.types.Range>", line 10, in structure_Range
        |     res['end'] = __c_structure_end(o['end'], __c_type_end)
        |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |   File "<cattrs generated structure lsprotocol.types.Position>", line 19, in structure_Position
        |     except Exception as exc: raise __c_cve('While structuring ' + 'Position', [exc], __cl)
        |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        | cattrs.errors.ClassValidationError: While structuring Position (1 sub-exception)
        | Structuring class Range @ attribute end
        +-+---------------- 1 ----------------
          | Traceback (most recent call last):
          |   File "<cattrs generated structure lsprotocol.types.Position>", line 16, in structure_Position
          |     return __cl(
          |             ^^^^
          |   File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
          |     __attr_validator_character(self, __attr_character, self.character)
          |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/lsprotocol/validators.py", line 44, in uinteger_validator
          |     raise ValueError(
          | ValueError: Position.character should be in range [0:2147483647], but was 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.
          +------------------------------------
      +---------------- 2 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 15, in structure_CodeActionParams
      |     res['context'] = __c_structure_context(o['context'], __c_type_context)
      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "<cattrs generated structure lsprotocol.types.CodeActionContext>", line 21, in structure_CodeActionContext
      |     if errors: raise __c_cve('While structuring ' + 'CodeActionContext', errors, __cl)
      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      | cattrs.errors.ClassValidationError: While structuring CodeActionContext (1 sub-exception)
      | Structuring class CodeActionParams @ attribute context
      +-+---------------- 1 ----------------
        | Exception Group Traceback (most recent call last):
        |   File "<cattrs generated structure lsprotocol.types.CodeActionContext>", line 5, in structure_CodeActionContext
        |     res['diagnostics'] = __c_structure_diagnostics(o['diagnostics'], __c_type_diagnostics)
        |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/cattrs/converters.py", line 545, in _structure_list
        |     raise IterableValidationError(
        | cattrs.errors.IterableValidationError: While structuring typing.List[lsprotocol.types.Diagnostic] (1 sub-exception)
        | Structuring class CodeActionContext @ attribute diagnostics
        +-+---------------- 1 ----------------
          | Exception Group Traceback (most recent call last):
          |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/cattrs/converters.py", line 535, in _structure_list
          |     res.append(handler(e, elem_type))
          |                ^^^^^^^^^^^^^^^^^^^^^
          |   File "<cattrs generated structure lsprotocol.types.Diagnostic>", line 56, in structure_Diagnostic
          |     if errors: raise __c_cve('While structuring ' + 'Diagnostic', errors, __cl)
          |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | cattrs.errors.ClassValidationError: While structuring Diagnostic (1 sub-exception)
          | Structuring typing.List[lsprotocol.types.Diagnostic] @ index 0
          +-+---------------- 1 ----------------
            | Exception Group Traceback (most recent call last):
            |   File "<cattrs generated structure lsprotocol.types.Diagnostic>", line 5, in structure_Diagnostic
            |     res['range'] = __c_structure_range(o['range'], __c_type_range)
            |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            |   File "<cattrs generated structure lsprotocol.types.Range>", line 14, in structure_Range
            |     if errors: raise __c_cve('While structuring ' + 'Range', errors, __cl)
            |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            | cattrs.errors.ClassValidationError: While structuring Range (1 sub-exception)
            | Structuring class Diagnostic @ attribute range
            +-+---------------- 1 ----------------
              | Traceback (most recent call last):
              |   File "<cattrs generated structure lsprotocol.types.Position>", line 16, in structure_Position
              |     return __cl(
              |             ^^^^
              |   File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
              |     __attr_validator_character(self, __attr_character, self.character)
              |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/lsprotocol/validators.py", line 44, in uinteger_validator
              |     raise ValueError(
              | ValueError: Position.character should be in range [0:2147483647], but was 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.
              | 
              | During handling of the above exception, another exception occurred:
              | 
              | Exception Group Traceback (most recent call last):
              |   File "<cattrs generated structure lsprotocol.types.Range>", line 10, in structure_Range
              |     res['end'] = __c_structure_end(o['end'], __c_type_end)
              |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              |   File "<cattrs generated structure lsprotocol.types.Position>", line 19, in structure_Position
              |     except Exception as exc: raise __c_cve('While structuring ' + 'Position', [exc], __cl)
              |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              | cattrs.errors.ClassValidationError: While structuring Position (1 sub-exception)
              | Structuring class Range @ attribute end
              +-+---------------- 1 ----------------
                | Traceback (most recent call last):
                |   File "<cattrs generated structure lsprotocol.types.Position>", line 16, in structure_Position
                |     return __cl(
                |             ^^^^
                |   File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
                |     __attr_validator_character(self, __attr_character, self.character)
                |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/lsprotocol/validators.py", line 44, in uinteger_validator
                |     raise ValueError(
                | ValueError: Position.character should be in range [0:2147483647], but was 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.
                +------------------------------------

Error receiving data
  + Exception Group Traceback (most recent call last):
  |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/pygls/protocol/json_rpc.py", line 329, in _deserialize_message
  |     return self._converter.structure(data, request_type)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/cattrs/converters.py", line 334, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>", line 26, in structure_TextDocumentCodeActionRequest
  |     if errors: raise __c_cve('While structuring ' + 'TextDocumentCodeActionRequest', errors, __cl)
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | cattrs.errors.ClassValidationError: While structuring TextDocumentCodeActionRequest (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>", line 10, in structure_TextDocumentCodeActionRequest
    |     res['params'] = __c_structure_params(o['params'], __c_type_params)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 31, in structure_CodeActionParams
    |     if errors: raise __c_cve('While structuring ' + 'CodeActionParams', errors, __cl)
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | cattrs.errors.ClassValidationError: While structuring CodeActionParams (2 sub-exceptions)
    | Structuring class TextDocumentCodeActionRequest @ attribute params
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 10, in structure_CodeActionParams
      |     res['range'] = __c_structure_range(o['range'], __c_type_range)
      |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "<cattrs generated structure lsprotocol.types.Range>", line 14, in structure_Range
      |     if errors: raise __c_cve('While structuring ' + 'Range', errors, __cl)
      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      | cattrs.errors.ClassValidationError: While structuring Range (1 sub-exception)
      | Structuring class CodeActionParams @ attribute range
      +-+---------------- 1 ----------------
        | Traceback (most recent call last):
        |   File "<cattrs generated structure lsprotocol.types.Position>", line 16, in structure_Position
        |     return __cl(
        |             ^^^^
        |   File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
        |     __attr_validator_character(self, __attr_character, self.character)
        |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/lsprotocol/validators.py", line 44, in uinteger_validator
        |     raise ValueError(
        | ValueError: Position.character should be in range [0:2147483647], but was 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.
        | 
        | During handling of the above exception, another exception occurred:
        | 
        | Exception Group Traceback (most recent call last):
        |   File "<cattrs generated structure lsprotocol.types.Range>", line 10, in structure_Range
        |     res['end'] = __c_structure_end(o['end'], __c_type_end)
        |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |   File "<cattrs generated structure lsprotocol.types.Position>", line 19, in structure_Position
        |     except Exception as exc: raise __c_cve('While structuring ' + 'Position', [exc], __cl)
        |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        | cattrs.errors.ClassValidationError: While structuring Position (1 sub-exception)
        | Structuring class Range @ attribute end
        +-+---------------- 1 ----------------
          | Traceback (most recent call last):
          |   File "<cattrs generated structure lsprotocol.types.Position>", line 16, in structure_Position
          |     return __cl(
          |             ^^^^
          |   File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
          |     __attr_validator_character(self, __attr_character, self.character)
          |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/lsprotocol/validators.py", line 44, in uinteger_validator
          |     raise ValueError(
          | ValueError: Position.character should be in range [0:2147483647], but was 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.
          +------------------------------------
      +---------------- 2 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 15, in structure_CodeActionParams
      |     res['context'] = __c_structure_context(o['context'], __c_type_context)
      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "<cattrs generated structure lsprotocol.types.CodeActionContext>", line 21, in structure_CodeActionContext
      |     if errors: raise __c_cve('While structuring ' + 'CodeActionContext', errors, __cl)
      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      | cattrs.errors.ClassValidationError: While structuring CodeActionContext (1 sub-exception)
      | Structuring class CodeActionParams @ attribute context
      +-+---------------- 1 ----------------
        | Exception Group Traceback (most recent call last):
        |   File "<cattrs generated structure lsprotocol.types.CodeActionContext>", line 5, in structure_CodeActionContext
        |     res['diagnostics'] = __c_structure_diagnostics(o['diagnostics'], __c_type_diagnostics)
        |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/cattrs/converters.py", line 545, in _structure_list
        |     raise IterableValidationError(
        | cattrs.errors.IterableValidationError: While structuring typing.List[lsprotocol.types.Diagnostic] (1 sub-exception)
        | Structuring class CodeActionContext @ attribute diagnostics
        +-+---------------- 1 ----------------
          | Exception Group Traceback (most recent call last):
          |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/cattrs/converters.py", line 535, in _structure_list
          |     res.append(handler(e, elem_type))
          |                ^^^^^^^^^^^^^^^^^^^^^
          |   File "<cattrs generated structure lsprotocol.types.Diagnostic>", line 56, in structure_Diagnostic
          |     if errors: raise __c_cve('While structuring ' + 'Diagnostic', errors, __cl)
          |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | cattrs.errors.ClassValidationError: While structuring Diagnostic (1 sub-exception)
          | Structuring typing.List[lsprotocol.types.Diagnostic] @ index 0
          +-+---------------- 1 ----------------
            | Exception Group Traceback (most recent call last):
            |   File "<cattrs generated structure lsprotocol.types.Diagnostic>", line 5, in structure_Diagnostic
            |     res['range'] = __c_structure_range(o['range'], __c_type_range)
            |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            |   File "<cattrs generated structure lsprotocol.types.Range>", line 14, in structure_Range
            |     if errors: raise __c_cve('While structuring ' + 'Range', errors, __cl)
            |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            | cattrs.errors.ClassValidationError: While structuring Range (1 sub-exception)
            | Structuring class Diagnostic @ attribute range
            +-+---------------- 1 ----------------
              | Traceback (most recent call last):
              |   File "<cattrs generated structure lsprotocol.types.Position>", line 16, in structure_Position
              |     return __cl(
              |             ^^^^
              |   File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
              |     __attr_validator_character(self, __attr_character, self.character)
              |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/lsprotocol/validators.py", line 44, in uinteger_validator
              |     raise ValueError(
              | ValueError: Position.character should be in range [0:2147483647], but was 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.
              | 
              | During handling of the above exception, another exception occurred:
              | 
              | Exception Group Traceback (most recent call last):
              |   File "<cattrs generated structure lsprotocol.types.Range>", line 10, in structure_Range
              |     res['end'] = __c_structure_end(o['end'], __c_type_end)
              |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              |   File "<cattrs generated structure lsprotocol.types.Position>", line 19, in structure_Position
              |     except Exception as exc: raise __c_cve('While structuring ' + 'Position', [exc], __cl)
              |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              | cattrs.errors.ClassValidationError: While structuring Position (1 sub-exception)
              | Structuring class Range @ attribute end
              +-+---------------- 1 ----------------
                | Traceback (most recent call last):
                |   File "<cattrs generated structure lsprotocol.types.Position>", line 16, in structure_Position
                |     return __cl(
                |             ^^^^
                |   File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
                |     __attr_validator_character(self, __attr_character, self.character)
                |   File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/lsprotocol/validators.py", line 44, in uinteger_validator
                |     raise ValueError(
                | ValueError: Position.character should be in range [0:2147483647], but was 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.
                +------------------------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/pygls/protocol/json_rpc.py", line 440, in data_received
    self._data_received(data)
  File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/pygls/protocol/json_rpc.py", line 472, in _data_received
    json.loads(
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user.name/Projects/rst-bug-repro/.venv-sphinx/lib/python3.11/site-packages/pygls/protocol/json_rpc.py", line 343, in _deserialize_message
    raise JsonRpcInvalidParams() from exc
pygls.exceptions.JsonRpcInvalidParams: Invalid Params
[Trace - 13:23:15] Received notification 'window/showMessage'.
Params: {
    "type": 1,
    "message": "Unexpected error in LSP server, see server's logs for details"
}


[Trace - 13:23:16] Sending notification '$/cancelRequest'.
Params: {
    "id": 49
}


Cancel notification for unknown message id "49"
```

**Comment by avoidik** [comment]
I guess this magic number is `DBL_MAX` or `MAX_VALUE` (max possible value for `double`) you could probably catch an edge-case when character is set to it

**Comment by avoidik** [comment]
I think the extension that has been causing this failure is `kevinglasson.cornflakes-linter`, everything is fine when I disable it

**Comment by alcarney** [comment]
Yes, this issue is identical to https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/429#issuecomment-1721600614, but this time it looks like the invalid value is coming from [here](https://github.com/elidhu/vscode-cornflakes-linter/blob/5460144ceb90e266173c4517f727a82e9654681e/src/features/flake8Linter.ts#L68), in the `kevinglasson.cornflakes-linter` extension.

Since it looks like this is a common pattern in VSCode extensions, I'll have to look at making `esbonio` less pedantic about these kinds of issues.

**Comment by lextm** [comment]
Close this since the culprit is something else.

**Comment by alcarney** [comment]
@avoidik `0.16.4` of `esbonio` is now available with a patch that should fix the issues you were seeing, let me know if it doesn't work for you! :)
