### ISSUE TITLE
[Bug]: Errors in output on Python 3.12 since `distutils` was removed

### ISSUE THREAD

**Issue by Jmennius** [vscode-restructuredtext/vscode-restructuredtext#439]
### Expected behavior

No errors in extension log.

### Actual behavior

A pop up says:
```
Python is not installed, or its version is too old. Esbonio language server requires 3.6 and above.
```
Preview seems to work.

### Detailed steps

Install Python 3.12 (via `pyenv`).
Create a venv, register with vscode.
Install `esbonio` and rst linters in venv.
Install `vscode-restructuredtext` extension or reload window, observe popup or check `OUTPUT` of `restructuredtext`.

### Extension information

v189.3.0

### Visual Studio Code information

1.84.2

### Operating system information

Linux: Fedora 39 + Ubuntu 18.04

### Python information

3.12.1

### Sphinx information

7.2.6

### Contents of conf.py

```python
no conf.py
```

### Relevant log output

```shell
[Log - 7:52:10 PM] Please visit https://docs.restructuredtext.net to learn how to configure the extension.
[Log - 7:52:10 PM] OS is linux
[Log - 7:52:10 PM] dist: ubuntu
[Log - 7:52:11 PM] Running cmd: "/path/to/project/backend/.venv/bin/python" -c "import sys; print(sys.version_info[0])"
[Log - 7:52:11 PM] Successful exec
[Log - 7:52:11 PM] Running cmd: "/path/to/project/backend/.venv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
[Log - 7:52:12 PM] Error
Command failed: "/path/to/project/backend/.venv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'

Error: Command failed: "/path/to/project/backend/.venv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'

	at ChildProcess.exithandler (node:child_process:420:12)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'

[Log - 7:52:12 PM] Running cmd: "/path/to/project/backend/.venv/bin/python" -c "import docutils;"
[Log - 7:52:12 PM] Successful exec
[Log - 7:52:12 PM] Running cmd: "/path/to/project/backend/.venv/bin/python" -c "import doc8.main;"
[Log - 7:52:12 PM] Successful exec
[Log - 7:52:12 PM] Enabled doc8 linting...
[Log - 7:52:12 PM] Running cmd: "/path/to/project/backend/.venv/bin/python" -c "import rstcheck;"
[Log - 7:52:12 PM] Successful exec
[Log - 7:52:12 PM] Enabled rstcheck linting...
[Log - 7:52:12 PM] [preview] set config to 
[Log - 7:52:12 PM] [linter] Execute: "/path/to/project/backend/.venv/bin/python" -m doc8.main "/path/to/project/README.rst" in /path/to/project.
[Log - 7:52:12 PM] [linter] Execute: "/path/to/project/backend/.venv/bin/python" -m rstcheck "/path/to/project/README.rst" in /path/to/project.
[Log - 7:52:12 PM] Running cmd: "/path/to/project/backend/.venv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
[Log - 7:52:13 PM] Running cmd: "/path/to/project/backend/.venv/bin/python" -c "import platform; from distutils.version import LooseVersion; print(LooseVersion(platform.python_version()) < LooseVersion('3.6.0'))"
[Log - 7:52:13 PM] Error
Command failed: "/path/to/project/backend/.venv/bin/python" -c "import platform; from distutils.version import LooseVersion; print(LooseVersion(platform.python_version()) < LooseVersion('3.6.0'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'

Error: Command failed: "/path/to/project/backend/.venv/bin/python" -c "import platform; from distutils.version import LooseVersion; print(LooseVersion(platform.python_version()) < LooseVersion('3.6.0'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'

	at ChildProcess.exithandler (node:child_process:420:12)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:322:12)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'

[Log - 7:52:13 PM] Error
Command failed: "/path/to/project/backend/.venv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'

Error: Command failed: "/path/to/project/backend/.venv/bin/python" -c "import esbonio.lsp; from distutils.version import LooseVersion; print(LooseVersion(esbonio.lsp.__version__) < LooseVersion('0.11.2'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'

	at ChildProcess.exithandler (node:child_process:420:12)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:322:12)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'

[Log - 7:52:13 PM] Running cmd: "/path/to/project/backend/.venv/bin/python" -c "import docutils;"
[Log - 7:52:14 PM] Successful exec
```

**Comment by Jmennius** [comment]
Hmm, I'm sorry, it does work, maybe it did not work because of missing linters.

**Comment by lextm** [comment]
The relevant code showed in the log is no longer used in 190.1.17 and above. So close this issue as not planned.

**Comment by Jmennius** [comment]
> The relevant code showed in the log is no longer used in 190.1.17 and above. So close this issue as not planned.

Thanks, will use pre-prelease for now.
